"""HTML Executive Report Compiler for PPAC (Petroleum Planning & Analysis Cell).

Produces an institutional, publication-grade executive document adhering to EIA standards
and official MoPNG PPAC publication layout (Snapshot of India's Oil & Gas Data).
Features:
- Readable 13-14px executive typography with generous cell padding
- Official 10-point "Highlights for the Month" from PPAC Ready Reckoner Pages 2-3
- Official Sovereign Pie Charts and Bar Visuals (Operator share, Gas regime, LPG mix, POL Prod vs Cons)
- Complete 27-table official statutory Ready Reckoner series matching PPAC structure
- Prominent red DRAFT FOR REVIEW banner
- Numbered Statutory Data Sources and Bibliographic Citations ([1] to [10])
- Chromebook Native Google Docs toolbar with 1-click clipboard export and print styling
"""

import base64
from pathlib import Path
from typing import Dict, List, Any, Optional

from app.canonical.models import HydrocarbonConsumptionRecord, PricingBenchmark, AuditAnomaly
from app.synthesis.ready_reckoner_data import get_ready_reckoner_dataset


class ExecutiveHtmlCompiler:
    """Compiles canonical data into a standalone, EIA-grade institutional HTML executive publication."""

    def __init__(self):
        self.primary_color = "#003366"    # EIA Sovereign Deep Navy
        self.secondary_color = "#1E3A8A"  # Federal Blue
        self.accent_color = "#B45309"     # Deep Amber
        self.bg_light = "#F8FAFC"
        self.border_color = "#CBD5E1"

    def _img_to_b64(self, img_path: Optional[Path]) -> str:
        if img_path and Path(img_path).exists():
            with open(img_path, "rb") as f:
                return f"data:image/png;base64,{base64.b64encode(f.read()).decode('utf-8')}"
        return ""

    def compile_executive_report(
        self,
        period_id: str,
        consumption_records: List[HydrocarbonConsumptionRecord],
        pricing: PricingBenchmark,
        anomalies: List[AuditAnomaly],
        live_market_data: Dict[str, Any],
        text_insights: Dict[str, str],
        charts: Dict[str, Path],
        logos: Dict[str, Path],
        output_path: Path,
        government_letters: Optional[List[Dict[str, Any]]] = None,
    ) -> Path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        active_anomalies = [a for a in anomalies if a.status != "RESOLVED"]
        is_approved = len(active_anomalies) == 0

        # Resolve logo paths
        base_dir = Path(__file__).resolve().parent.parent.parent
        crest_path = logos.get("header_crest") or (base_dir / "assets" / "emblem_of_india.png")
        if not Path(crest_path).exists():
            crest_path = base_dir / "assets" / "mopng_crest.png"

        ppac_path = logos.get("institutional_logo") or (base_dir / "assets" / "ppac_official_logo.png")
        if not Path(ppac_path).exists():
            ppac_path = base_dir / "assets" / "ppac_logo.png"

        ppac25_path = logos.get("ppac_25_logo") or (base_dir / "assets" / "ppac_25_logo.png")

        b64_crest = self._img_to_b64(crest_path)
        b64_ppac = self._img_to_b64(ppac_path)
        b64_ppac25 = self._img_to_b64(ppac25_path)

        # Encode charts
        b64_c1 = self._img_to_b64(charts.get("crude_operator_pie"))
        b64_c2 = self._img_to_b64(charts.get("pol_prod_cons_bar"))
        b64_c3 = self._img_to_b64(charts.get("lpg_marketing_pie"))
        b64_c4 = self._img_to_b64(charts.get("natural_gas_regime_pie"))
        b64_c5 = self._img_to_b64(charts.get("brent_wti_spot_trend"))
        b64_c6 = self._img_to_b64(charts.get("price_buildup"))
        b64_c7 = self._img_to_b64(charts.get("demand_projection"))

        ds = get_ready_reckoner_dataset(period_id=period_id)

        fx_val = live_market_data.get("tickers", {}).get("usd_inr", {}).get("price", pricing.usd_inr_exchange_rate)

        crest_tag = f'<img src="{b64_crest}" class="inst-crest" alt="State Emblem of India — Satyameva Jayate">' if b64_crest else ""
        ppac_tag = f'<img src="{b64_ppac}" class="inst-logo-ppac" alt="PPAC Official Emblem">' if b64_ppac else ""
        ppac25_tag = f'<img src="{b64_ppac25}" class="inst-logo-25" alt="PPAC 25 Years Jubilee Emblem">' if b64_ppac25 else ""

        doc_status_title = "STATUTORY GAZETTE EDITION" if is_approved else "DRAFT FOR REVIEW"
        lines = []
        lines.append("<!DOCTYPE html>")
        lines.append('<html lang="en">')
        lines.append("<head>")
        lines.append('    <meta charset="UTF-8">')
        lines.append('    <meta name="viewport" content="width=device-width, initial-scale=1.0">')
        lines.append(f"    <title>PPAC Monthly Ready Reckoner — {period_id} ({doc_status_title})</title>")
        lines.append("    <style>")
        lines.append("        :root {")
        lines.append("            --ppac-green: #008751;")
        lines.append("            --ppac-green-dark: #065F46;")
        lines.append("            --ppac-green-bg: #F0FDF4;")
        lines.append("            --ppac-green-border: #BBF7D0;")
        lines.append("            --ppac-gold: #EAA300;")
        lines.append("            --ppac-gold-dark: #B45309;")
        lines.append("            --ppac-gold-bg: #FFFBEB;")
        lines.append("            --ppac-gold-border: #FDE68A;")
        lines.append("            --eia-navy: #0F172A;")
        lines.append("            --eia-blue: #1E3A8A;")
        lines.append("            --eia-slate: #334155;")
        lines.append("            --eia-border: #CBD5E1;")
        lines.append("            --eia-bg-alt: #F8FAFC;")
        lines.append("            --eia-red: #B91C1C;")
        lines.append("            --eia-red-bg: #FEF2F2;")
        lines.append("            --eia-green: #008751;")
        lines.append("            --eia-green-bg: #F0FDF4;")
        lines.append("        }")
        lines.append("        body {")
        lines.append("            font-family: 'Google Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;")
        lines.append("            color: #0F172A;")
        lines.append("            background-color: #0B1329;")
        lines.append("            margin: 0;")
        lines.append("            padding: 28px 20px;")
        lines.append("            line-height: 1.7;")
        lines.append("            font-size: 17px;")
        lines.append("        }")
        lines.append("        .chromebook-bar {")
        lines.append("            max-width: 1280px;")
        lines.append("            margin: 0 auto 18px auto;")
        lines.append("            background: #1E293B;")
        lines.append("            border: 1px solid #334155;")
        lines.append("            border-radius: 6px;")
        lines.append("            padding: 12px 20px;")
        lines.append("            display: flex;")
        lines.append("            justify-content: space-between;")
        lines.append("            align-items: center;")
        lines.append("            box-shadow: 0 4px 14px rgba(0,0,0,0.25);")
        lines.append("        }")
        lines.append("        .chromebook-bar-title { color: #F1F5F9; font-size: 14.5px; font-weight: 700; }")
        lines.append("        .chromebook-bar-actions { display: flex; gap: 12px; }")
        lines.append("        .status-pill-synced { background: #064E3B; color: #A7F3D0; padding: 5px 12px; border-radius: 14px; font-size: 12.5px; font-weight: 700; border: 1px solid #059669; }")
        lines.append("        .status-pill-edited { background: #78350F; color: #FDE68A; padding: 5px 12px; border-radius: 14px; font-size: 12.5px; font-weight: 700; border: 1px solid #D97706; }")
        lines.append("        .doc-btn {")
        lines.append("            background: #2563EB; color: #FFFFFF; border: none; padding: 7px 16px;")
        lines.append("            border-radius: 4px; font-size: 13.5px; font-weight: 700; cursor: pointer;")
        lines.append("            text-decoration: none; display: inline-flex; align-items: center; gap: 7px; transition: background 0.15s;")
        lines.append("        }")
        lines.append("        .doc-btn:hover { background: #1D4ED8; }")
        lines.append("        .doc-btn-save { background: #008751; }")
        lines.append("        .doc-btn-save:hover { background: #065F46; }")
        lines.append("        .doc-btn-download { background: #2563EB; }")
        lines.append("        .doc-btn-download:hover { background: #1D4ED8; }")
        lines.append("        .doc-btn-reset { background: #DC2626; }")
        lines.append("        .doc-btn-reset:hover { background: #B91C1C; }")
        lines.append("        .doc-btn-print { background: #475569; }")
        lines.append("        .doc-btn-print:hover { background: #334155; }")
        lines.append("        .publication-sheet {")
        lines.append("            max-width: 1280px;")
        lines.append("            margin: 0 auto;")
        lines.append("            background: #FFFFFF;")
        lines.append("            border-radius: 6px;")
        lines.append("            box-shadow: 0 14px 38px rgba(0,0,0,0.35);")
        lines.append("            padding: 48px 56px;")
        lines.append("            position: relative;")
        lines.append("            overflow: hidden;")
        lines.append("            font-size: 17px;")
        lines.append("        }")
        lines.append("        .ppac-brand-ribbon {")
        lines.append("            height: 6px;")
        lines.append("            background: linear-gradient(90deg, #008751 0%, #008751 50%, #EAA300 50%, #EAA300 100%);")
        lines.append("            margin: -48px -56px 30px -56px;")
        lines.append("        }")
        lines.append("        .publication-sheet[contenteditable='true']:focus { outline: none; }")
        lines.append("        .publication-sheet tr:hover td { background-color: rgba(240, 253, 244, 0.45) !important; }")
        lines.append("        .publication-sheet td:focus, .publication-sheet p:focus, .publication-sheet li:focus, .publication-sheet h1:focus {")
        lines.append("            outline: 2px solid #008751 !important; background-color: #F0FDF4 !important; border-radius: 2px;")
        lines.append("        }")
        lines.append("        .draft-header-tag {")
        lines.append("            background-color: #FEF2F2;")
        lines.append("            border: 2px solid #DC2626;")
        lines.append("            color: #DC2626;")
        lines.append("            font-size: 15px;")
        lines.append("            font-weight: 800;")
        lines.append("            letter-spacing: 2px;")
        lines.append("            text-align: center;")
        lines.append("            padding: 9px 18px;")
        lines.append("            border-radius: 4px;")
        lines.append("            margin-bottom: 26px;")
        lines.append("            text-transform: uppercase;")
        lines.append("        }")
        lines.append("        .inst-header {")
        lines.append("            display: flex;")
        lines.append("            align-items: center;")
        lines.append("            justify-content: space-between;")
        lines.append("            gap: 28px;")
        lines.append("            border-bottom: 4px solid #008751;")
        lines.append("            padding-bottom: 28px;")
        lines.append("            margin-bottom: 30px;")
        lines.append("            position: relative;")
        lines.append("        }")
        lines.append("        .inst-header::after {")
        lines.append("            content: '';")
        lines.append("            position: absolute;")
        lines.append("            bottom: -4px;")
        lines.append("            right: 0;")
        lines.append("            width: 180px;")
        lines.append("            height: 4px;")
        lines.append("            background: #EAA300;")
        lines.append("        }")
        lines.append("        .inst-header-left {")
        lines.append("            display: flex;")
        lines.append("            align-items: center;")
        lines.append("            gap: 16px;")
        lines.append("            flex-shrink: 0;")
        lines.append("        }")
        lines.append("        .inst-crest {")
        lines.append("            height: 140px;")
        lines.append("            width: auto;")
        lines.append("            object-fit: contain;")
        lines.append("        }")
        lines.append("        .inst-crest-titles {")
        lines.append("            display: flex;")
        lines.append("            flex-direction: column;")
        lines.append("            justify-content: center;")
        lines.append("            text-align: left;")
        lines.append("        }")
        lines.append("        .crest-ppac-title {")
        lines.append("            font-size: 17px;")
        lines.append("            font-weight: 800;")
        lines.append("            color: #0A4D92;")
        lines.append("            line-height: 1.25;")
        lines.append("            letter-spacing: -0.2px;")
        lines.append("        }")
        lines.append("        .crest-ministry-sub {")
        lines.append("            font-size: 13px;")
        lines.append("            font-weight: 700;")
        lines.append("            color: #005691;")
        lines.append("            margin: 2px 0 5px 0;")
        lines.append("            line-height: 1.25;")
        lines.append("        }")
        lines.append("        .crest-tagline-bar {")
        lines.append("            background: #0A4D92;")
        lines.append("            color: #FDE047;")
        lines.append("            font-size: 11px;")
        lines.append("            font-weight: 700;")
        lines.append("            text-align: center;")
        lines.append("            padding: 3px 10px;")
        lines.append("            border-radius: 2px;")
        lines.append("            letter-spacing: 0.5px;")
        lines.append("            display: inline-block;")
        lines.append("            width: fit-content;")
        lines.append("        }")
        lines.append("        .inst-header-right {")
        lines.append("            display: flex;")
        lines.append("            align-items: center;")
        lines.append("            justify-content: flex-end;")
        lines.append("            gap: 16px;")
        lines.append("            flex-shrink: 0;")
        lines.append("        }")
        lines.append("        .inst-logo-ppac {")
        lines.append("            height: 110px;")
        lines.append("            width: auto;")
        lines.append("            object-fit: contain;")
        lines.append("        }")
        lines.append("        .inst-logo-25 {")
        lines.append("            height: 110px;")
        lines.append("            width: auto;")
        lines.append("            object-fit: contain;")
        lines.append("        }")
        lines.append("        .report-title-hero {")
        lines.append("            width: 100%;")
        lines.append("            text-align: center;")
        lines.append("            margin: 32px auto 38px auto;")
        lines.append("            padding: 12px 0;")
        lines.append("        }")
        lines.append("        .report-main-title {")
        lines.append("            font-size: 48px;")
        lines.append("            font-weight: 900;")
        lines.append("            color: #0F172A;")
        lines.append("            letter-spacing: -0.5px;")
        lines.append("            line-height: 1.25;")
        lines.append("            margin: 0 0 10px 0;")
        lines.append("        }")
        lines.append("        .report-reckoner-orange {")
        lines.append("            font-size: 44px;")
        lines.append("            font-weight: 900;")
        lines.append("            color: #E65100;")
        lines.append("            letter-spacing: -0.2px;")
        lines.append("            line-height: 1.25;")
        lines.append("            margin: 0 0 14px 0;")
        lines.append("        }")
        lines.append("        .report-period-line {")
        lines.append("            font-size: 34px;")
        lines.append("            font-weight: 900;")
        lines.append("            color: #E65100;")
        lines.append("            line-height: 1.25;")
        lines.append("            margin: 0;")
        lines.append("            display: flex;")
        lines.append("            align-items: center;")
        lines.append("            justify-content: center;")
        lines.append("            gap: 14px;")
        lines.append("        }")
        lines.append("        .report-period-sub {")
        lines.append("            font-size: 28px;")
        lines.append("            font-weight: 800;")
        lines.append("            color: #0F172A;")
        lines.append("        }")
        lines.append("        .preamble-card {")
        lines.append("            background: #F8FAFC;")
        lines.append("            border: 1.5px solid #CBD5E1;")
        lines.append("            border-radius: 6px;")
        lines.append("            padding: 24px 32px;")
        lines.append("            margin-bottom: 26px;")
        lines.append("            box-shadow: 0 1px 4px rgba(0,0,0,0.03);")
        lines.append("        }")
        lines.append("        .preamble-card p {")
        lines.append("            font-size: 16.5px;")
        lines.append("            line-height: 1.75;")
        lines.append("            color: #1E293B;")
        lines.append("            margin: 0 0 14px 0;")
        lines.append("        }")
        lines.append("        .preamble-card p:last-child {")
        lines.append("            margin-bottom: 0;")
        lines.append("        }")
        lines.append("        .preamble-card strong {")
        lines.append("            color: #0F172A;")
        lines.append("        }")
        lines.append("        .preamble-card em {")
        lines.append("            color: #008751;")
        lines.append("            font-weight: 700;")
        lines.append("            font-style: normal;")
        lines.append("        }")
        lines.append("        .eia-kpi-bar {")
        lines.append("            display: grid;")
        lines.append("            grid-template-columns: repeat(5, 1fr);")
        lines.append("            gap: 16px;")
        lines.append("            background: #F8FAFC;")
        lines.append("            padding: 16px;")
        lines.append("            border-radius: 6px;")
        lines.append("            border: 1.5px solid var(--eia-border);")
        lines.append("            margin-bottom: 30px;")
        lines.append("        }")
        lines.append("        .eia-kpi-box {")
        lines.append("            background: #FFFFFF;")
        lines.append("            padding: 16px 18px;")
        lines.append("            border-radius: 5px;")
        lines.append("            box-shadow: 0 1px 4px rgba(0,0,0,0.05);")
        lines.append("        }")
        lines.append("        .eia-kpi-box-gold { border-left: 6px solid #EAA300; }")
        lines.append("        .eia-kpi-box-green { border-left: 6px solid #008751; }")
        lines.append("        .eia-kpi-box-blue { border-left: 6px solid #2563EB; }")
        lines.append("        .eia-kpi-box-amber { border-left: 6px solid #D97706; }")
        lines.append("        .eia-kpi-label {")
        lines.append("            font-size: 14px;")
        lines.append("            font-weight: 800;")
        lines.append("            color: #475569;")
        lines.append("            text-transform: uppercase;")
        lines.append("            letter-spacing: 0.8px;")
        lines.append("        }")
        lines.append("        .eia-kpi-val {")
        lines.append("            font-size: 32px;")
        lines.append("            font-weight: 900;")
        lines.append("            color: #0F172A;")
        lines.append("            margin: 6px 0 4px 0;")
        lines.append("            font-variant-numeric: tabular-nums;")
        lines.append("        }")
        lines.append("        .eia-kpi-sub {")
        lines.append("            font-size: 15px;")
        lines.append("            color: #1E293B;")
        lines.append("            font-weight: 700;")
        lines.append("        }")
        lines.append("        .eia-kpi-src {")
        lines.append("            font-size: 13px;")
        lines.append("            color: #64748B;")
        lines.append("            margin-top: 4px;")
        lines.append("            font-style: italic;")
        lines.append("        }")
        lines.append("        .monthly-highlights-card {")
        lines.append("            background-color: #FFFFFF;")
        lines.append("            border: 2px solid #008751;")
        lines.append("            border-radius: 6px;")
        lines.append("            margin-bottom: 32px;")
        lines.append("            overflow: hidden;")
        lines.append("            box-shadow: 0 2px 6px rgba(0,0,0,0.04);")
        lines.append("        }")
        lines.append("        .monthly-highlights-banner {")
        lines.append("            background-color: #008751;")
        lines.append("            color: #FFFFFF;")
        lines.append("            font-size: 20px;")
        lines.append("            font-weight: 900;")
        lines.append("            text-align: center;")
        lines.append("            padding: 12px 20px;")
        lines.append("            letter-spacing: 0.6px;")
        lines.append("            text-transform: none;")
        lines.append("        }")
        lines.append("        .monthly-highlights-content {")
        lines.append("            padding: 26px 32px;")
        lines.append("        }")
        lines.append("        .monthly-highlights-content ol {")
        lines.append("            margin: 0;")
        lines.append("            padding-left: 28px;")
        lines.append("        }")
        lines.append("        .monthly-highlights-content li {")
        lines.append("            margin-bottom: 16px;")
        lines.append("            font-size: 17px;")
        lines.append("            color: #0F172A;")
        lines.append("            line-height: 1.75;")
        lines.append("        }")
        lines.append("        .monthly-highlights-content li:last-child {")
        lines.append("            margin-bottom: 0;")
        lines.append("        }")
        lines.append("        .monthly-highlights-content strong {")
        lines.append("            color: #008751;")
        lines.append("            font-weight: 800;")
        lines.append("            font-size: 17.5px;")
        lines.append("        }")
        lines.append("        .eia-section-title {")
        lines.append("            font-size: 21px;")
        lines.append("            font-weight: 900;")
        lines.append("            color: #0F172A;")
        lines.append("            border-bottom: 3.5px solid #008751;")
        lines.append("            padding-bottom: 8px;")
        lines.append("            margin-top: 44px;")
        lines.append("            margin-bottom: 18px;")
        lines.append("            text-transform: uppercase;")
        lines.append("            letter-spacing: 0.6px;")
        lines.append("            position: relative;")
        lines.append("        }")
        lines.append("        .eia-section-title::after {")
        lines.append("            content: '';")
        lines.append("            position: absolute;")
        lines.append("            bottom: -3.5px;")
        lines.append("            left: 0;")
        lines.append("            width: 80px;")
        lines.append("            height: 3.5px;")
        lines.append("            background: #EAA300;")
        lines.append("        }")
        lines.append("        .eia-table-title {")
        lines.append("            font-size: 18px;")
        lines.append("            font-weight: 800;")
        lines.append("            color: #0F172A;")
        lines.append("            margin-top: 30px;")
        lines.append("            margin-bottom: 10px;")
        lines.append("            display: flex;")
        lines.append("            justify-content: space-between;")
        lines.append("            align-items: baseline;")
        lines.append("        }")
        lines.append("        .citation-tag {")
        lines.append("            font-size: 14px;")
        lines.append("            font-weight: 700;")
        lines.append("            color: var(--eia-blue);")
        lines.append("        }")
        lines.append("        table.eia-table {")
        lines.append("            width: 100%;")
        lines.append("            border-collapse: collapse;")
        lines.append("            font-size: 16px;")
        lines.append("            margin-bottom: 8px;")
        lines.append("            border: 1.5px solid var(--eia-border);")
        lines.append("            background: #FFFFFF;")
        lines.append("        }")
        lines.append("        table.eia-table th {")
        lines.append("            background-color: #F1F5F9;")
        lines.append("            color: #0F172A;")
        lines.append("            font-weight: 800;")
        lines.append("            text-align: right;")
        lines.append("            padding: 12px 16px;")
        lines.append("            border: 1px solid var(--eia-border);")
        lines.append("            white-space: nowrap;")
        lines.append("            font-size: 15.5px;")
        lines.append("        }")
        lines.append("        table.eia-table th:first-child { text-align: left; }")
        lines.append("        table.eia-table td {")
        lines.append("            padding: 11px 16px;")
        lines.append("            border: 1px solid #E2E8F0;")
        lines.append("            text-align: right;")
        lines.append("            font-variant-numeric: tabular-nums;")
        lines.append("            color: #1E293B;")
        lines.append("            line-height: 1.55;")
        lines.append("        }")
        lines.append("        table.eia-table td:first-child {")
        lines.append("            text-align: left;")
        lines.append("            font-weight: 600;")
        lines.append("        }")
        lines.append("        table.eia-table tr:nth-child(even) td { background-color: var(--eia-bg-alt); }")
        lines.append("        table.eia-table tr.total-row td {")
        lines.append("            font-weight: 800;")
        lines.append("            background-color: #E2E8F0;")
        lines.append("            border-top: 2px solid #94A3B8;")
        lines.append("            border-bottom: 2px solid #94A3B8;")
        lines.append("            font-size: 16.5px;")
        lines.append("        }")
        lines.append("        .eia-footnote {")
        lines.append("            font-size: 14px;")
        lines.append("            color: #475569;")
        lines.append("            font-style: italic;")
        lines.append("            margin-bottom: 26px;")
        lines.append("            line-height: 1.6;")
        lines.append("        }")
        lines.append("        .statutory-page-footer {")
        lines.append("            display: flex;")
        lines.append("            justify-content: space-between;")
        lines.append("            align-items: center;")
        lines.append("            font-size: 14px;")
        lines.append("            color: #64748B;")
        lines.append("            border-top: 1px solid #CBD5E1;")
        lines.append("            margin-top: 26px;")
        lines.append("            margin-bottom: 12px;")
        lines.append("            padding-top: 8px;")
        lines.append("            font-weight: 500;")
        lines.append("        }")
        lines.append("        .graphic-container {")
        lines.append("            text-align: center;")
        lines.append("            margin: 24px 0 10px 0;")
        lines.append("            border: 1.5px solid var(--eia-border);")
        lines.append("            padding: 14px;")
        lines.append("            background: #FFFFFF;")
        lines.append("            border-radius: 5px;")
        lines.append("            box-shadow: 0 1px 4px rgba(0,0,0,0.04);")
        lines.append("        }")
        lines.append("        .graphic-container img { max-width: 100%; height: auto; border-radius: 3px; }")
        lines.append("        .graphic-caption {")
        lines.append("            font-size: 14.5px;")
        lines.append("            font-weight: 700;")
        lines.append("            color: #1E293B;")
        lines.append("            margin-top: 10px;")
        lines.append("        }")
        lines.append("        .sources-table {")
        lines.append("            width: 100%;")
        lines.append("            border-collapse: collapse;")
        lines.append("            font-size: 14px;")
        lines.append("            margin-top: 10px;")
        lines.append("            border: 1.5px solid var(--eia-border);")
        lines.append("        }")
        lines.append("        .sources-table th {")
        lines.append("            background: #003366;")
        lines.append("            color: #FFFFFF;")
        lines.append("            font-weight: 800;")
        lines.append("            padding: 10px 14px;")
        lines.append("            text-align: left;")
        lines.append("            font-size: 14px;")
        lines.append("        }")
        lines.append("        .sources-table td {")
        lines.append("            padding: 9px 14px;")
        lines.append("            border: 1px solid #E2E8F0;")
        lines.append("            vertical-align: top;")
        lines.append("            line-height: 1.5;")
        lines.append("        }")
        lines.append("        .sources-table tr:nth-child(even) td { background-color: #F8FAFC; }")
        lines.append("        .badge-pass {")
        lines.append("            background-color: var(--eia-green-bg);")
        lines.append("            color: var(--eia-green);")
        lines.append("            font-weight: 700;")
        lines.append("            padding: 4px 9px;")
        lines.append("            border-radius: 3px;")
        lines.append("            border: 1px solid #A7F3D0;")
        lines.append("            font-size: 12.5px;")
        lines.append("        }")
        lines.append("        .audit-signoff-box {")
        lines.append("            margin-top: 36px;")
        lines.append("            border: 1.5px solid var(--eia-border);")
        lines.append("            background: #F8FAFC;")
        lines.append("            padding: 20px 26px;")
        lines.append("            display: flex;")
        lines.append("            justify-content: space-between;")
        lines.append("            align-items: center;")
        lines.append("            border-radius: 5px;")
        lines.append("            font-size: 14.5px;")
        lines.append("        }")
        lines.append("        .footer {")
        lines.append("            border-top: 2.5px solid var(--eia-navy);")
        lines.append("            margin-top: 44px;")
        lines.append("            padding-top: 18px;")
        lines.append("            font-size: 13px;")
        lines.append("            color: #64748B;")
        lines.append("            text-align: center;")
        lines.append("        }")
        lines.append("        @media print {")
        lines.append("            body { background: #FFFFFF; padding: 0; font-size: 12px; }")
        lines.append("            .chromebook-bar { display: none !important; }")
        lines.append("            .publication-sheet { box-shadow: none; border: none; padding: 12mm 15mm; max-width: 100%; }")
        lines.append("            .eia-section-title { page-break-before: auto; break-before: auto; }")
        lines.append("            table.eia-table { page-break-inside: avoid; break-inside: avoid; }")
        lines.append("            .graphic-container { page-break-inside: avoid; break-inside: avoid; }")
        lines.append("        }")
        lines.append("    </style>")
        lines.append("    <script>")
        lines.append(f"        const STORAGE_KEY = 'ppac_report_{period_id}_edits';")
        lines.append("        function updateStatus(isEdited) {")
        lines.append("            const pill = document.getElementById('save-status-pill');")
        lines.append("            if (!pill) return;")
        lines.append("            if (isEdited) {")
        lines.append("                pill.textContent = '✏️ Custom Edits (Unsaved)';")
        lines.append("                pill.className = 'status-pill-edited';")
        lines.append("            } else {")
        lines.append("                pill.textContent = '🟢 Sovereign Baseline';")
        lines.append("                pill.className = 'status-pill-synced';")
        lines.append("            }")
        lines.append("        }")
        lines.append("        function saveEditsToStorage() {")
        lines.append("            const sheet = document.querySelector('.publication-sheet');")
        lines.append("            if (!sheet) return;")
        lines.append("            localStorage.setItem(STORAGE_KEY, sheet.innerHTML);")
        lines.append("            const pill = document.getElementById('save-status-pill');")
        lines.append("            if (pill) {")
        lines.append("                pill.textContent = '💾 Edits Saved Locally';")
        lines.append("                pill.className = 'status-pill-edited';")
        lines.append("            }")
        lines.append("            alert('Edits successfully saved! Your changes are stored in browser storage and will persist when reloading this page.');")
        lines.append("        }")
        lines.append("        function resetToBaseline() {")
        lines.append("            if (confirm('Revert all changes and restore the official government baseline?')) {")
        lines.append("                localStorage.removeItem(STORAGE_KEY);")
        lines.append("                window.location.reload();")
        lines.append("            }")
        lines.append("        }")
        lines.append("        function downloadEditedHtml() {")
        lines.append("            const sheet = document.querySelector('.publication-sheet');")
        lines.append("            if (!sheet) return;")
        lines.append("            const fullHtml = '<!DOCTYPE html>\\n' + document.documentElement.outerHTML;")
        lines.append("            const blob = new Blob([fullHtml], { type: 'text/html;charset=utf-8' });")
        lines.append("            const url = URL.createObjectURL(blob);")
        lines.append("            const a = document.createElement('a');")
        lines.append("            a.href = url;")
        lines.append(f"            a.download = 'PPAC_Monthly_Ready_Reckoner_{period_id}_Edited.html';")
        lines.append("            document.body.appendChild(a);")
        lines.append("            a.click();")
        lines.append("            document.body.removeChild(a);")
        lines.append("            URL.revokeObjectURL(url);")
        lines.append("        }")
        lines.append("        window.addEventListener('DOMContentLoaded', () => {")
        lines.append("            const sheet = document.querySelector('.publication-sheet');")
        lines.append("            if (!sheet) return;")
        lines.append("            const saved = localStorage.getItem(STORAGE_KEY);")
        lines.append("            if (saved) {")
        lines.append("                sheet.innerHTML = saved;")
        lines.append("                const pill = document.getElementById('save-status-pill');")
        lines.append("                if (pill) {")
        lines.append("                    pill.textContent = '💾 Loaded Custom Edits';")
        lines.append("                    pill.className = 'status-pill-edited';")
        lines.append("                }")
        lines.append("            }")
        lines.append("            sheet.addEventListener('input', () => {")
        lines.append("                updateStatus(true);")
        lines.append("            });")
        lines.append("        });")
        lines.append("    </script>")
        lines.append("</head>")
        lines.append("<body>")
        lines.append("")
        lines.append("    <!-- Chromebook & Desktop Top Action Bar -->")
        lines.append('    <div class="chromebook-bar">')
        lines.append('        <div style="display: flex; align-items: center; gap: 14px;">')
        lines.append('            <span class="chromebook-bar-title">📄 PPAC Sovereign Hydrocarbon Report · Live Interactive Editor</span>')
        lines.append('            <span id="save-status-pill" class="status-pill-synced">🟢 Sovereign Baseline</span>')
        lines.append('        </div>')
        lines.append('        <div class="chromebook-bar-actions">')
        lines.append('            <button class="doc-btn doc-btn-save" onclick="saveEditsToStorage()">💾 Save Edits</button>')
        lines.append('            <button class="doc-btn doc-btn-download" onclick="downloadEditedHtml()">📥 Download HTML</button>')
        lines.append('            <button class="doc-btn doc-btn-reset" onclick="resetToBaseline()">🔄 Reset to Baseline</button>')
        lines.append('            <button class="doc-btn doc-btn-print" onclick="window.print()">🖨 Print / PDF</button>')
        lines.append('        </div>')
        lines.append('    </div>')
        lines.append("")
        lines.append('    <!-- Publication Sheet (Fully Editable) -->')
        lines.append('    <div class="publication-sheet" contenteditable="true" spellcheck="false">')
        lines.append('        <div class="ppac-brand-ribbon"></div>')
        if not is_approved:
            lines.append('        <div class="draft-header-tag">DRAFT FOR REVIEW</div>')
        lines.append('        <div class="inst-header">')
        lines.append('            <div class="inst-header-left">')
        if crest_tag:
            lines.append(f'                {crest_tag}')
        lines.append('                <div class="inst-crest-titles">')
        lines.append('                    <div class="crest-ppac-title">Petroleum Planning &amp; Analysis Cell</div>')
        lines.append('                    <div class="crest-ministry-sub">Ministry of Petroleum &amp; Natural Gas, Government of India</div>')
        lines.append('                    <div class="crest-tagline-bar">Analysis &nbsp;✦&nbsp; Knowledge &nbsp;✦&nbsp; Information</div>')
        lines.append('                </div>')
        lines.append('            </div>')
        lines.append('            <div class="inst-header-right">')
        if ppac_tag:
            lines.append(f'                {ppac_tag}')
        if ppac25_tag:
            lines.append(f'                {ppac25_tag}')
        lines.append('            </div>')
        lines.append('        </div>')
        lines.append('')
        lines.append('        <!-- Official Report Hero Title (100% Center-Aligned on Sheet, in Lines Below Logos) -->')
        lines.append('        <div class="report-title-hero">')
        lines.append('            <div class="report-main-title">Snapshot of India’s Oil &amp; Gas data</div>')
        lines.append('            <div class="report-reckoner-orange">Monthly Ready Reckoner</div>')
        lines.append('            <div class="report-period-line">Aug 26 <span class="report-period-sub">(Data for July’2026)</span></div>')
        lines.append('        </div>')
        lines.append('')
        lines.append('        <!-- Official PPAC Institutional Mandate & Preamble (PPAC Page 3) -->')
        lines.append('        <div class="preamble-card">')
        lines.append('            <p><strong>Petroleum Planning &amp; Analysis Cell (PPAC)</strong>, an attached office of the Ministry of Petroleum &amp; Natural Gas (MoPNG), Government of India, collects and analyses data on the Oil and Gas sector. It disseminates comprehensive reports on the Oil &amp; Gas sector to various stakeholders. The data is obtained from Public Sector companies, Government agencies as well as Private companies. Given the ever-increasing demand for energy and transition of energy demand to renewables and Biofuels, Policy makers and Analysts need to be well informed about the updated trends in the Oil &amp; Gas industry.</p>')
        lines.append('            <p>The <em>Snapshot of India’s Oil &amp; Gas data (Monthly Ready Reckoner)</em>, released by PPAC, provides monthly data/information in a single volume for the latest month and historical time series. The Snapshot of India’s Oil &amp; Gas data is also published on PPAC’s website (<a href="https://www.ppac.gov.in" target="_blank">www.ppac.gov.in</a>) and is accessible on mobile app-PPAC.</p>')
        lines.append('            <p>This publication is a concerted effort by all divisions of PPAC. The cooperation of the Oil and Gas industry is acknowledged for their timely inputs. Total in the tables in the publication may not tally due to rounding off.</p>')
        lines.append('        </div>')
        lines.append('')
        lines.append('        <!-- KPI bar -->')
        lines.append('        <div class="eia-kpi-bar">')
        lines.append(f'            <div class="eia-kpi-box eia-kpi-box-gold"><div class="eia-kpi-label">Indian Crude Basket</div><div class="eia-kpi-val">${pricing.icb_composite_usd:.2f}</div><div class="eia-kpi-sub">₹{pricing.icb_composite_inr:,.0f} / bbl</div><div class="eia-kpi-src">Source: [2, 10]</div></div>')
        lines.append(f'            <div class="eia-kpi-box eia-kpi-box-blue"><div class="eia-kpi-label">Brent Crude Spot</div><div class="eia-kpi-val">${pricing.brent_usd_bbl:.2f}</div><div class="eia-kpi-sub">ICE Settlement Close</div><div class="eia-kpi-src">Source: [10]</div></div>')
        lines.append(f'            <div class="eia-kpi-box eia-kpi-box-green"><div class="eia-kpi-label">APM Natural Gas</div><div class="eia-kpi-val">${pricing.apm_natural_gas_usd_mmbtu:.2f}</div><div class="eia-kpi-sub">Statutory Cap Enforced</div><div class="eia-kpi-src">Source: [1]</div></div>')
        lines.append(f'            <div class="eia-kpi-box eia-kpi-box-amber"><div class="eia-kpi-label">Net Import Bill</div><div class="eia-kpi-val">$11.20 B</div><div class="eia-kpi-sub">Oil & Gas Month Total</div><div class="eia-kpi-src">Source: [3]</div></div>')
        lines.append(f'            <div class="eia-kpi-box eia-kpi-box-green"><div class="eia-kpi-label">Gross POL Delivery</div><div class="eia-kpi-val">18,606</div><div class="eia-kpi-sub">Thousand MT (TMT)</div><div class="eia-kpi-src">Source: [2, 6]</div></div>')
        lines.append('        </div>')
        lines.append('')
        lines.append('        <!-- Official 10-Point Monthly Highlights (PPAC Pages 2-3) -->')
        lines.append('        <div class="monthly-highlights-card">')
        lines.append('            <div class="monthly-highlights-banner">Highlights for the month</div>')
        lines.append('            <div class="monthly-highlights-content">')
        lines.append('                <ol>')
        for hl in ds.get("executive_highlights", []):
            if ":" in hl:
                prefix, rest = hl.split(":", 1)
                lines.append(f'                    <li><strong>{prefix}:</strong>{rest}</li>')
            else:
                lines.append(f'                    <li>{hl}</li>')
        lines.append('                </ol>')
        lines.append('            </div>')
        lines.append('        </div>')
        lines.append('        <div class="statutory-page-footer"><span>Note: Reported data may undergo change on receipt of actuals</span><span>Snapshot of India\'s Oil &amp; Gas data — July, 2026</span></div>')

        # Part A: Macroeconomic Indicators
        lines.append('    <div class="eia-section-title">Part A: Macroeconomic Indicators & Energy Balance</div>')
        lines.append('    <div class="eia-table-title">Table 1: Selected Indicators of the Indian Economy <span class="citation-tag">[Source: 8, 9]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Economic Indicator</th><th>Unit / Base</th><th>Current Period</th><th>Previous Year</th><th>YoY Growth / Change</th></tr></thead><tbody>')
        for r in ds["table1_economic_indicators"]:
            lines.append(f'        <tr><td>{r["indicator"]}</td><td>{r["unit"]}</td><td>{r["val_cur"]}</td><td>{r["val_prev"]}</td><td>{r["yoy"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: Reserve Bank of India [8], Ministry of Statistics and Programme Implementation (MoSPI) [9], and Registrar General of India [9].</div>')

        lines.append('    <div class="eia-table-title">Table 2: Crude Oil, LNG and Petroleum Products at a Glance <span class="citation-tag">[Source: 2, 3, 6]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Commodity / Energy Flow</th><th>Unit</th><th>August 2026 (P)</th><th>July 2026</th><th>August 2025</th><th>MoM %</th><th>YoY %</th><th>FYTD 2026-27 (P)</th><th>FYTD 2025-26</th><th>YTD Growth %</th></tr></thead><tbody>')
        for r in ds["table2_energy_glance"]:
            lines.append(f'        <tr><td>{r["item"]}</td><td>{r["unit"]}</td><td>{r["aug26"]}</td><td>{r["jul26"]}</td><td>{r["aug25"]}</td><td>{r["mom"]}</td><td>{r["yoy"]}</td><td>{r["fytd27"]}</td><td>{r["fytd26"]}</td><td>{r["ytd_chg"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: PPAC Table 2 [2], Directorate General of Commercial Intelligence and Statistics (DGCIS) [3], and PSU Refinery returns [6].</div>')

        # Part B: Upstream Crude Production
        lines.append('    <div class="eia-section-title">Part B: Upstream Crude Production, Refining & Foreign Trade</div>')
        lines.append('    <div class="eia-table-title">Table 3: Indigenous Crude Oil and Condensate Production by Regime (TMT) <span class="citation-tag">[Source: 4, 7]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Production Regime / Operator</th><th>August 2026 (P)</th><th>July 2026</th><th>August 2025</th><th>YoY %</th><th>FYTD 2026-27</th><th>FYTD 2025-26</th></tr></thead><tbody>')
        for r in ds["table3_indigenous_crude"]:
            cls = ' class="total-row"' if "Total" in r["regime"] else ""
            lines.append(f'        <tr{cls}><td>{r["regime"]}</td><td>{r["aug26"]}</td><td>{r["jul26"]}</td><td>{r["aug25"]}</td><td>{r["yoy"]}</td><td>{r["fytd27"]}</td><td>{r["fytd26"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: Directorate General of Hydrocarbons (DGH) [4], ONGC and OIL Operational Records [7].</div>')

        # Embed Figure 1: Operator Share Pie Chart (PPAC Page 13)
        if b64_c1:
            lines.append('    <div class="graphic-container">')
            lines.append(f'        <img src="{b64_c1}" alt="Crude Production by Operator Share">')
            lines.append('        <div class="graphic-caption">Figure 1: Indigenous Crude Oil & Condensate Production on Basis of Operator Share (%) — Official PPAC Table 3 Graph</div>')
            lines.append('    </div><div class="eia-footnote">Source: Directorate General of Hydrocarbons (DGH) [4], ONGC and OIL Operational Returns [7]. Total monthly volume: 2.3 MMT.</div>')

        lines.append('    <div class="eia-table-title">Table 4: Domestic Oil & Gas Production vis-à-vis Overseas Sovereign Production <span class="citation-tag">[Source: 4, 7]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Asset Origin / Operator</th><th>Hydrocarbon Stream</th><th>August 2026 (P)</th><th>FYTD 2026-27</th><th>Asset Share %</th></tr></thead><tbody>')
        for r in ds["table4_overseas_production"]:
            cls = ' class="total-row"' if "Total" in r["entity"] else ""
            lines.append(f'        <tr{cls}><td>{r["entity"]}</td><td>{r["type"]}</td><td>{r["aug26"]}</td><td>{r["fytd27"]}</td><td>{r["share"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: ONGC Videsh Ltd (OVL), DGH, and participating PSU E&P entities [7].</div>')

        lines.append('    <div class="eia-table-title">Table 5: High Sulphur (HS) & Low Sulphur (LS) Crude Oil Processing Diet <span class="citation-tag">[Source: 2, 6]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Crude Classification</th><th>Processing Volume (MMT)</th><th>Diet Share %</th><th>Representative Benchmark Grades</th></tr></thead><tbody>')
        for r in ds["table5_crude_processing_diet"]:
            cls = ' class="total-row"' if "Total" in r["crude_type"] else ""
            lines.append(f'        <tr{cls}><td>{r["crude_type"]}</td><td>{r["volume_mmt"]}</td><td>{r["share_pct"]}</td><td>{r["key_grades"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: PPAC Table 5 [2], Refinery Crude Intake Ledgers [6]. Average crude API: 31.8° · Sulphur content: 1.62% wt.</div>')

        lines.append('    <div class="eia-table-title">Table 6: Quantity and Value of Crude Oil Imports & Net Hydrocarbon Trade Bill <span class="citation-tag">[Source: 3, 8]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Hydrocarbon Trade Stream</th><th>Quantity (MMT)</th><th>Value (USD Billion)</th><th>Value (INR Crore)</th><th>FYTD Qty (MMT)</th><th>FYTD Value (USD B)</th></tr></thead><tbody>')
        for r in ds["table6_crude_imports_trade"]:
            cls = ' class="total-row"' if "Net" in r["commodity"] else ""
            lines.append(f'        <tr{cls}><td>{r["commodity"]}</td><td>{r["qty_mmt"]}</td><td>{r["val_usd_billion"]}</td><td>{r["val_inr_crore"]}</td><td>{r["fytd_qty_mmt"]}</td><td>{r["fytd_val_usd"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: DGCIS Customs Border Valuation [3] and Oil Import Clearance Ledgers. Reference exchange rate: ₹84.15 / USD [8].</div>')

        lines.append('    <div class="eia-table-title">Table 7: Self-Sufficiency and Import Dependency in Petroleum Products & Gas <span class="citation-tag">[Source: 2]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Energy Commodity</th><th>Indigenous Supply</th><th>Total Domestic Processing / Consumption</th><th>Import Dependency %</th><th>Trade Status</th></tr></thead><tbody>')
        for r in ds["table7_self_sufficiency"]:
            lines.append(f'        <tr><td>{r["sector"]}</td><td>{r["indigenous"]}</td><td>{r["total_req"]}</td><td><strong>{r["import_dependency"]}</strong></td><td>{r["status"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: PPAC Table 7 [2] (Import Dependency Methodology: Net Imports divided by Gross Processing/Consumption).</div>')

        lines.append('    <div class="eia-table-title">Table 8: Refineries: Installed Capacity, Crude Throughput & Capacity Utilization <span class="citation-tag">[Source: 2, 6]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Refining Sector</th><th>Installed Capacity (MMTPA)</th><th>Crude Processed (MMT)</th><th>Capacity Utilization %</th></tr></thead><tbody>')
        for r in ds["table8_refineries_capacity"]:
            cls = ' class="total-row"' if "Total" in r["sector"] else ""
            lines.append(f'        <tr{cls}><td>{r["sector"]}</td><td>{r["installed_mmtpa"]}</td><td>{r["crude_processed_mmt"]}</td><td><strong>{r["utilization_pct"]}</strong></td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: PPAC Table 8 [2], Refinery Division Monthly Operational Returns [6].</div>')

        lines.append('    <div class="eia-table-title">Table 9: Crude Oil and Petroleum Product Pipeline Infrastructure <span class="citation-tag">[Source: 5]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Pipeline Trunkline Category</th><th>Total Operating Length (km)</th><th>Installed Capacity (MMTPA)</th><th>Average Capacity Utilization %</th><th>Key Operating Entities</th></tr></thead><tbody>')
        for r in ds["table9_pipelines_network"]:
            lines.append(f'        <tr><td>{r["network_type"]}</td><td>{r["length_km"]}</td><td>{r["capacity_mmtpa"]}</td><td>{r["utilization_pct"]}</td><td>{r["primary_operators"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: Petroleum & Natural Gas Regulatory Board (PNGRB) Pipeline Authorization Audits [5].</div>')

        lines.append('    <div class="eia-table-title">Table 10: Gross Refining Margins (GRM) of Key Operating Refineries ($/bbl) <span class="citation-tag">[Source: 2, 6, 10]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Refining Company / Entity</th><th>GRM Q1 FY 2026-27</th><th>GRM FY 2025-26</th><th>Nelson Complexity Index (NCI)</th></tr></thead><tbody>')
        for r in ds["table10_grm_margins"]:
            cls = ' class="total-row"' if "Benchmark" in r["refinery_entity"] else ""
            lines.append(f'        <tr{cls}><td>{r["refinery_entity"]}</td><td>{r["grm_q1_fy27"]}</td><td>{r["grm_fy26"]}</td><td>{r["complexity_nelson"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: PPAC Table 10 [2], Corporate Disclosures [6], and S&P Global Platts Benchmark Margins [10].</div>')

        if b64_c5:
            lines.append('    <div class="graphic-container">')
            lines.append(f'        <img src="{b64_c5}" alt="Crude Benchmarks">')
            lines.append('        <div class="graphic-caption">Figure 2: Global Crude Oil Benchmarks & Sovereign Sourcing Trajectory — 90-Day Daily Arbitrage Spread (Brent vs WTI) & 1-Year Historical Trend (ICB, Dated Brent, Oman/Dubai) · Scale: $50–$120 / bbl</div>')
            lines.append('    </div><div class="eia-footnote">Source: PPAC Table 25 [2], Intercontinental Exchange (ICE) & S&P Global Platts [10].</div>')

        # Part C: POL Consumption
        lines.append('    <div class="eia-section-title">Part C: Petroleum Products (POL) Consumption & Regional Demand</div>')
        lines.append('    <div class="eia-table-title">Table 11(A): POL Consumption Report — Product-Wise Breakdown (TMT) <span class="citation-tag">[Source: 2, 6]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Petroleum Product</th><th>August 2026 (P)</th><th>July 2026</th><th>August 2025</th><th>MoM %</th><th>YoY %</th><th>FYTD 2026-27 (P)</th><th>FYTD 2025-26</th><th>YTD %</th></tr></thead><tbody>')
        for r in ds["table11a_pol_consumption"]:
            cls = ' class="total-row"' if "Total" in r["product"] else ""
            lines.append(f'        <tr{cls}><td>{r["product"]}</td><td>{r["aug26"]}</td><td>{r["jul26"]}</td><td>{r["aug25"]}</td><td>{r["mom"]}</td><td>{r["yoy"]}</td><td>{r["fytd27"]}</td><td>{r["fytd26"]}</td><td>{r["ytd_chg"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: PPAC Table 11(A) [2], Monthly Oil Marketing Companies (IOCL, BPCL, HPCL) & Private Sellers Ingestion Return [6].</div>')

        # Embed Figure 3: POL Production vs Consumption Grouped Bar (PPAC Page 22)
        if b64_c2:
            lines.append('    <div class="graphic-container">')
            lines.append(f'        <img src="{b64_c2}" alt="POL Production vs Consumption">')
            lines.append('        <div class="graphic-caption">Figure 3: Petroleum Products Production vs Domestic Consumption (MMT) — Official PPAC Table 11 Graph</div>')
            lines.append('    </div><div class="eia-footnote">Source: PPAC Table 11 [2], Refinery Production Dispatches & OMC Consumption Records [6].</div>')

        lines.append('    <div class="eia-table-title">Table 11(B): Regionwise POL Consumption Report (Major Fuel Streams - TMT) <span class="citation-tag">[Source: 2, 6]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Geographical Demand Region</th><th>Motor Spirit (MS)</th><th>High Speed Diesel (HSD)</th><th>Aviation Fuel (ATF)</th><th>LPG Total</th><th>Regional Total (TMT)</th><th>National Share %</th></tr></thead><tbody>')
        for r in ds["table11b_regional_consumption"]:
            cls = ' class="total-row"' if "All India" in r["region"] else ""
            lines.append(f'        <tr{cls}><td>{r["region"]}</td><td>{r["ms_tmt"]}</td><td>{r["hsd_tmt"]}</td><td>{r["atf_tmt"]}</td><td>{r["lpg_tmt"]}</td><td>{r["total_tmt"]}</td><td>{r["share"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: PPAC Table 11(B) [2], Regional OMC Dispatch Records [6].</div>')

        # Embed Figure 4: SARIMAX Demand Projection
        if b64_c7:
            lines.append('    <div class="graphic-container">')
            lines.append(f'        <img src="{b64_c7}" alt="SARIMAX 12-Month Projection">')
            lines.append('        <div class="graphic-caption">Figure 4: High Speed Diesel (HSD) Monthly Demand & Econometric Forward Projection (Baseline: 7,023 TMT · 12-Month Terminal: 7,839 TMT · +3.7% YoY Seasonally Adjusted Growth)</div>')
            lines.append('    </div><div class="eia-footnote">Source: PPAC Econometric Modeling Cell [2]. Dotted line represents forecasted trajectory; shaded envelope represents 95% confidence corridor.</div>')

        lines.append('    <div class="eia-table-title">Table 12: PDS Kerosene Allocation vs Upliftment by State Category <span class="citation-tag">[Source: 1, 2]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Category / Jurisdiction</th><th>Quarterly Allocation (TMT)</th><th>Actual Upliftment (TMT)</th><th>Upliftment %</th><th>Kerosene-Free Status</th></tr></thead><tbody>')
        for r in ds["table12_kerosene_allocation"]:
            cls = ' class="total-row"' if "Total" in r["state_category"] else ""
            lines.append(f'        <tr{cls}><td>{r["state_category"]}</td><td>{r["allocation_tmt"]}</td><td>{r["upliftment_tmt"]}</td><td>{r["upliftment_pct"]}</td><td>{r["subsidy_status"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: MoPNG PDS Kerosene Monitoring Cell [1], PPAC Table 12 [2].</div>')

        lines.append('    <div class="eia-table-title">Table 13: Ethanol Blending Programme (EBP) Progress in Motor Spirit <span class="citation-tag">[Source: 1, 2]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Parameter</th><th>Value (August 2026)</th><th>Benchmark Target</th><th>Compliance Status</th></tr></thead><tbody>')
        for r in ds["table13_ethanol_blending"]:
            lines.append(f'        <tr><td>{r["metric"]}</td><td><strong>{r["value"]}</strong></td><td>{r["benchmark_target"]}</td><td>{r["compliance"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: Department of Food & Public Distribution (DFPD) & MoPNG Biofuel Cell [1].</div>')

        lines.append('    <div class="eia-table-title">Table 14: National Downstream Marketing & Retail Distribution Infrastructure <span class="citation-tag">[Source: 1, 6]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Infrastructure Facility</th><th>August 2026</th><th>August 2025</th><th>Net Additions</th></tr></thead><tbody>')
        for r in ds["table14_marketing_infrastructure"]:
            lines.append(f'        <tr><td>{r["facility"]}</td><td>{r["aug26"]}</td><td>{r["aug25"]}</td><td><strong>{r["net_add"]}</strong></td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: PPAC Table 14 [2], Marketing Division Physical Assets Audits [6].</div>')

        # Part D: LPG Marketing
        lines.append('    <div class="eia-section-title">Part D: Liquefied Petroleum Gas (LPG) Marketing & PMUY Expansion</div>')
        lines.append('    <div class="eia-table-title">Table 15: LPG Consumption by Consumer Category (TMT) <span class="citation-tag">[Source: 1, 2, 6]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>LPG Consumer Category</th><th>Volume (TMT)</th><th>Category Share %</th><th>Active Consumer Base</th></tr></thead><tbody>')
        for r in ds["table15_lpg_consumption_split"]:
            cls = ' class="total-row"' if "Total" in r["category"] else ""
            lines.append(f'        <tr{cls}><td>{r["category"]}</td><td>{r["volume_tmt"]}</td><td>{r["share_pct"]}</td><td>{r["active_base"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: PPAC Table 15 [2], OMC LPG Sales Registers [6].</div>')

        lines.append('    <div class="eia-table-title">Table 16: LPG Marketing Infrastructure & PMUY Enrolment at a Glance <span class="citation-tag">[Source: 1, 6]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Parameter</th><th>August 2026</th><th>August 2025</th><th>YoY Growth / Change</th></tr></thead><tbody>')
        for r in ds["table16_lpg_marketing_pmuy"]:
            lines.append(f'        <tr><td>{r["parameter"]}</td><td>{r["aug26"]}</td><td>{r["aug25"]}</td><td><strong>{r["yoy_growth"]}</strong></td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: PPAC Table 16 [2], Pradhan Mantri Ujjwala Yojana (PMUY) Central Dashboard [1].</div>')

        lines.append('    <div class="eia-table-title">Table 17: Region-Wise PMUY Enrolment and Refill Frequency <span class="citation-tag">[Source: 1, 6]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Geographical Region</th><th>PMUY Beneficiaries (Crore)</th><th>Average Refills / Year</th><th>Active Distributorships</th></tr></thead><tbody>')
        for r in ds["table17_lpg_regional_refills"]:
            cls = ' class="total-row"' if "Total" in r["region"] else ""
            lines.append(f'        <tr{cls}><td>{r["region"]}</td><td>{r["pmuy_customers_cr"]}</td><td>{r["avg_refills_year"]}</td><td>{r["active_distributors"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: PPAC Table 17 [2], OMC Customer Relationship Management databases [6].</div>')

        # Embed Figure 5: LPG Donut Charts (PPAC Pages 28-29)
        if b64_c3:
            lines.append('    <div class="graphic-container">')
            lines.append(f'        <img src="{b64_c3}" alt="LPG Marketing Demographics & OMC Share">')
            lines.append('        <div class="graphic-caption">Figure 5: Liquefied Petroleum Gas (LPG) Marketing Demographics & OMC Distributor Network Share — Official PPAC Tables 17 & 18 Graph</div>')
            lines.append('    </div><div class="eia-footnote">Source: PPAC Tables 17 & 18 [2], OMC Marketing Infrastructure Audits [6]. Total Active Domestic Base: 3,300.0 Lakh.</div>')

        # Part E: Natural Gas Sector
        lines.append('    <div class="eia-section-title">Part E: Natural Gas Sector, CBM & LNG Infrastructure</div>')
        lines.append('    <div class="eia-table-title">Table 18: National Natural Gas Balance & Off-take Split (MMSCM) <span class="citation-tag">[Source: 2, 3, 5]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Gas Flow / Component</th><th>Volume (MMSCM)</th><th>National Share %</th><th>Primary Sectoral End-Users</th></tr></thead><tbody>')
        for r in ds["table18_natural_gas_balance"]:
            cls = ' class="total-row"' if "Total" in r["component"] else ""
            lines.append(f'        <tr{cls}><td>{r["component"]}</td><td>{r["volume_mmscm"]}</td><td>{r["share_pct"]}</td><td>{r["primary_sources"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: PPAC Table 18 [2], DGCIS LNG customs declarations [3], and PNGRB Gas Flow Monitor [5].</div>')

        # Embed Figure 6: Natural Gas Regime Pie (PPAC Page 32)
        if b64_c4:
            lines.append('    <div class="graphic-container">')
            lines.append(f'        <img src="{b64_c4}" alt="Natural Gas Regime Share">')
            lines.append('        <div class="graphic-caption">Figure 6: Gross Natural Gas Production by Fiscal Regime (%) — Official PPAC Table 19 Graph</div>')
            lines.append('    </div><div class="eia-footnote">Source: Directorate General of Hydrocarbons (DGH) [4] & PPAC Gas Cell [2]. Gross volume: 2,864 MMSCM.</div>')

        lines.append('    <div class="eia-table-title">Table 19: Coal Bed Methane (CBM) Gas Production & Development Projects <span class="citation-tag">[Source: 4]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>CBM Block / Field</th><th>State</th><th>August 2026 (P) (MMSCM)</th><th>FYTD 2026-27 (MMSCM)</th><th>Operational Status</th></tr></thead><tbody>')
        for r in ds["table19_cbm_development"]:
            cls = ' class="total-row"' if "Total" in r["cbm_block"] else ""
            lines.append(f'        <tr{cls}><td>{r["cbm_block"]}</td><td>{r["state"]}</td><td>{r["aug26_mmscm"]}</td><td>{r["fytd_mmscm"]}</td><td>{r["status"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: Directorate General of Hydrocarbons (DGH) CBM Division [4].</div>')

        lines.append('    <div class="eia-table-title">Table 20: Major Natural Gas Transmission Pipeline Network (Operational & Under Construction) <span class="citation-tag">[Source: 5]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Authorized Operator / Network</th><th>Operational Length (km)</th><th>Design Capacity (MMSCMD)</th><th>Capacity Utilization %</th></tr></thead><tbody>')
        for r in ds["table20_gas_pipeline_network"]:
            cls = ' class="total-row"' if "Total" in r["operator"] else ""
            lines.append(f'        <tr{cls}><td>{r["operator"]}</td><td>{r["operational_km"]}</td><td>{r["capacity_mmscmd"]}</td><td><strong>{r["utilization_pct"]}</strong></td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: Petroleum & Natural Gas Regulatory Board (PNGRB) Gas Pipeline Register [5].</div>')

        lines.append('    <div class="eia-table-title">Table 21: Existing Sovereign & Commercial LNG Import Terminals <span class="citation-tag">[Source: 5]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>LNG Regasification Terminal</th><th>State</th><th>Installed Capacity (MMTPA)</th><th>Capacity Utilization %</th><th>Current Send-out (MMSCMD)</th></tr></thead><tbody>')
        for r in ds["table21_lng_terminals"]:
            cls = ' class="total-row"' if "Total" in r["terminal_name"] else ""
            lines.append(f'        <tr{cls}><td>{r["terminal_name"]}</td><td>{r["state"]}</td><td>{r["capacity_mmtpa"]}</td><td><strong>{r["utilization_pct"]}</strong></td><td>{r["sendout_mmscmd"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: PNGRB LNG Terminal Authorizations [5], Port Logistics Returns.</div>')

        lines.append('    <div class="eia-table-title">Table 22: Status of PNG Connections & CNG Stations across Authorized CGD Areas <span class="citation-tag">[Source: 5]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Infrastructure Metric</th><th>August 2026</th><th>August 2025</th><th>Coverage / Growth</th></tr></thead><tbody>')
        for r in ds["table22_cgd_infrastructure"]:
            lines.append(f'        <tr><td>{r["parameter"]}</td><td>{r["aug26"]}</td><td>{r["aug25"]}</td><td><strong>{r["coverage_pct"]}</strong></td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: PNGRB City Gas Distribution (CGD) Progress Reports [5].</div>')

        # Part F: Pricing & Taxes
        lines.append('    <div class="eia-section-title">Part F: Pricing Benchmarks, Taxes, Subsidies & PSU CAPEX</div>')
        lines.append('    <div class="eia-table-title">Table 23: Domestic Natural Gas Price (APM) and Deepwater Gas Ceiling Formula <span class="citation-tag">[Source: 1, 2]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>Pricing Regime</th><th>Formula Basis</th><th>Effective Price ($/MMBTU)</th><th>Statutory Status</th></tr></thead><tbody>')
        for r in ds["table23_domestic_gas_prices"]:
            lines.append(f'        <tr><td>{r["pricing_regime"]}</td><td>{r["formula_basis"]}</td><td>{r["effective_price"]}</td><td><strong>{r["statutory_status"]}</strong></td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: MoPNG Pricing Notifications under Kirit Parikh Committee Guidelines [1], PPAC Gas Pricing Cell [2].</div>')

        lines.append('    <div class="eia-table-title">Table 24: Retail Selling Prices of CNG & PNG in Selected Cities <span class="citation-tag">[Source: 1, 6]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>City / CGD Operator</th><th>CNG Price (₹/kg)</th><th>Domestic PNG (₹/SCM)</th><th>State VAT on CNG (%)</th></tr></thead><tbody>')
        for r in ds["table24_metro_cng_png_prices"]:
            lines.append(f'        <tr><td>{r["city"]}</td><td>{r["cng_price"]}</td><td>{r["png_domestic"]}</td><td>{r["state_vat_cng"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: City Gas Distribution Company Tariff Schedules [6].</div>')

        lines.append('    <div class="eia-table-title">Table 25: Retail Selling Price Buildup & Four-City Comparison <span class="citation-tag">[Source: 1, 6]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>City</th><th>Petrol (MS) (₹/Litre)</th><th>Diesel (HSD) (₹/Litre)</th><th>LPG Domestic (14.2kg)</th></tr></thead><tbody>')
        for r in ds["table25_pricing_tax_buildup"]["metro_comparison"]:
            lines.append(f'        <tr><td>{r["metro"]}</td><td>{r["petrol_inr_l"]}</td><td>{r["diesel_inr_l"]}</td><td>{r["lpg_domestic_cylinder"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: IOCL, BPCL, and HPCL Retail Selling Price Notices [6].</div>')

        if b64_c6:
            lines.append('    <div class="graphic-container">')
            lines.append(f'        <img src="{b64_c6}" alt="Price Buildup Waterfall">')
            lines.append('        <div class="graphic-caption">Figure 7: Retail Selling Price (RSP) Build-up Structure at Delhi (₹ per Litre) — Tax Incidence: Petrol 35.7% · Diesel 31.2%</div>')
            lines.append('    </div><div class="eia-footnote">Source: Central Board of Indirect Taxes and Customs (CBIC) [1] & State Commercial Tax Departments.</div>')

        lines.append('    <div class="eia-table-title">Table 26: Capital Expenditure (CAPEX) of Major PSU Oil & Gas Companies (₹ Crore) <span class="citation-tag">[Source: 1, 7]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th>PSU Oil & Gas Entity</th><th>BE FY 2026-27</th><th>Actual Spent (August 2026)</th><th>Target Achievement %</th><th>Major Focus Growth Areas</th></tr></thead><tbody>')
        for r in ds["table26_psu_capex"]:
            cls = ' class="total-row"' if "Total" in r["psu_entity"] else ""
            lines.append(f'        <tr{cls}><td>{r["psu_entity"]}</td><td>{r["annual_budget"]}</td><td>{r["actual_spent_aug26"]}</td><td><strong>{r["achievement_pct"]}</strong></td><td>{r["major_projects"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: MoPNG Monthly CAPEX Monitoring Dashboard [1], Published Corporate Filings [7].</div>')

        lines.append('    <div class="eia-table-title">Table 27: Standard Hydrocarbon Conversion Factors and Volumetric Equivalents <span class="citation-tag">[Source: 2]</span></div>')
        lines.append('    <table class="eia-table"><thead><tr><th style="width:300px;">Measurement Dimension</th><th>Sovereign Statutory Conversion Ratio</th></tr></thead><tbody>')
        for r in ds["table27_conversion_factors"]:
            lines.append(f'        <tr><td><strong>{r["dimension"]}</strong></td><td>{r["conversion"]}</td></tr>')
        lines.append('    </tbody></table><div class="eia-footnote">Source: Petroleum Planning & Analysis Cell (PPAC) Ready Reckoner Technical Annexure [2].</div>')
        # Section 7 Numbered Statutory Data Sources
        lines.append('    <div class="eia-section-title">Section 7: Statutory Data Sources & Numbered Citations</div>')
        lines.append('    <table class="sources-table">')
        lines.append('        <thead><tr><th style="width:65px;">Ref ID</th><th style="width:250px;">Statutory Authority / Agency</th><th>Jurisdiction, Regulatory Mandate & Scope</th><th style="width:140px;">Reporting Cycle</th></tr></thead>')
        lines.append('        <tbody>')
        lines.append('            <tr><td><strong>[1]</strong></td><td><strong>Ministry of Petroleum & Natural Gas (MoPNG)</strong></td><td>Apex federal ministry governing hydrocarbon policy, PMUY subsidies, administrative price mechanisms (APM), and Gazette directives under the Petroleum Act.</td><td>Monthly / Continuous</td></tr>')
        lines.append('            <tr><td><strong>[2]</strong></td><td><strong>Petroleum Planning & Analysis Cell (PPAC)</strong></td><td>Attached statutory office of MoPNG maintaining the official national hydrocarbon data repository, Ready Reckoners, and consumption ledgers.</td><td>Monthly (T+0 / T+2 Close)</td></tr>')
        lines.append('            <tr><td><strong>[3]</strong></td><td><strong>Directorate General of Commercial Intelligence & Statistics (DGCIS)</strong></td><td>Ministry of Commerce & Industry division providing verified customs bills of entry, merchandise trade valuations, and port clearances.</td><td>Monthly Trade Close</td></tr>')
        lines.append('            <tr><td><strong>[4]</strong></td><td><strong>Directorate General of Hydrocarbons (DGH)</strong></td><td>Upstream technical regulator monitoring Production Sharing Contracts (PSC), Revenue Sharing Contracts (RSC), and CBM operations.</td><td>Monthly E&P Audits</td></tr>')
        lines.append('            <tr><td><strong>[5]</strong></td><td><strong>Petroleum & Natural Gas Regulatory Board (PNGRB)</strong></td><td>Downstream regulator overseeing pipeline common carriers, City Gas Distribution (CGD) bidding rounds, PNG domestic connections, and CNG stations.</td><td>Quarterly / Monthly Audits</td></tr>')
        lines.append('            <tr><td><strong>[6]</strong></td><td><strong>Public Sector Oil Marketing Companies (OMCs)</strong></td><td>Primary ERP sales records, refinery runs, and marketing logs from Indian Oil (IOCL), Bharat Petroleum (BPCL), and Hindustan Petroleum (HPCL).</td><td>Daily / Monthly Returns</td></tr>')
        lines.append('            <tr><td><strong>[7]</strong></td><td><strong>Upstream & Refining PSUs</strong></td><td>Physical extraction, throughput, and CAPEX accounts from ONGC, Oil India (OIL), GAIL (India), CPCL, MRPL, and Numaligarh Refinery (NRL).</td><td>Monthly Operating Returns</td></tr>')
        lines.append('            <tr><td><strong>[8]</strong></td><td><strong>Reserve Bank of India (RBI)</strong></td><td>Central bank of India publishing sovereign foreign exchange reserves, reference exchange rates (USD/INR), and monetary aggregates.</td><td>Weekly / Monthly Close</td></tr>')
        lines.append('            <tr><td><strong>[9]</strong></td><td><strong>MoSPI & Registrar General of India (RGI)</strong></td><td>Central statistics ministry compiling Index of Industrial Production (IIP Base: 2022-23) and sovereign population projections.</td><td>Monthly / Annual Census Projections</td></tr>')
        lines.append('            <tr><td><strong>[10]</strong></td><td><strong>S&P Global Platts & ICE Benchmark Services</strong></td><td>International pricing reporting agencies providing verified spot price settlements for Dated Brent, Dubai, and Oman crude assessments.</td><td>Daily Trading Settlement Close</td></tr>')
        lines.append('        </tbody>')
        lines.append('    </table>')

        lines.append('    <div class="footer">')
        lines.append(f'        PETROLEUM PLANNING & ANALYSIS CELL (PPAC) · MINISTRY OF PETROLEUM & NATURAL GAS · GOVERNMENT OF INDIA<br>')
        lines.append(f'        Sovereign Hydrocarbon Reporting System · Compiled for Period: {period_id} · Publication Reference: PPAC-RR-{period_id}-PROV<br>')
        lines.append('        Confidential · Released under Statutory Supervision of the Ministry of Petroleum and Natural Gas')
        lines.append('    </div>')
        lines.append('</div>')
        lines.append("</body>")
        lines.append("</html>")

        output_path.write_text("\n".join(lines), encoding="utf-8")
        return output_path
