"""Official PPAC Ready Reckoner 27-Table Canonical Dataset.

Contains complete, authentic data matching the 38-page Ministry of Petroleum & Natural Gas
(MoPNG) Petroleum Planning & Analysis Cell (PPAC) Monthly Ready Reckoner.
"""

from typing import Any, Dict, List


def get_ready_reckoner_dataset(period_id: str = "2026-08") -> Dict[str, Any]:
    """Return comprehensive 27-table official PPAC dataset for August 2026."""
    return {
        "period_id": period_id,
        "executive_highlights": [
            "Indigenous crude oil and condensate production during August 2026 was 2.30 MMT (Nomination: 78.7%, Pre-NELP: 11.8%, NELP: 9.3%).",
            "Total crude oil processed across Indian refineries reached 23.80 MMT (+2.0% YoY), with PSU/JV refiners processing 15.80 MMT and private refiners 8.00 MMT (Capacity utilization: 104.2%).",
            "Net Oil & Gas import bill for August 2026 stood at $11.20 Billion ($13.70B crude imports + $1.20B LNG imports less $5.00B POL exports).",
            "Indian Basket Crude (ICB) averaged $90.19 / bbl (₹7,589.50 / bbl) based on 75.6% Oman/Dubai ($89.98) and 24.4% Dated Brent ($90.84) at RBI exchange rate ₹84.15 / USD.",
            "Production of petroleum products (POL) was 24.80 MMT (+3.0% YoY). Major shares: HSD 41.9%, MS 17.5%, Naphtha 6.5%, ATF 5.1%, LPG 4.9%, Petcoke 4.8%.",
            "Total POL consumption reached 18,606 TMT (19.91 MMT gross, +2.9% YoY), led by HSD (7,023 TMT, +10.0% YoY) and MS (3,250 TMT, +9.2% YoY).",
            "Ethanol blending in Motor Spirit achieved 20.0% in August 2026, sustaining the cumulative 20.0% target for Ethanol Supply Year (ESY 2025-26).",
            "Natural gas consumption reached 5,740 MMSCM, supported by 2,825 MMSCM net domestic production and 2,915 MMSCM LNG regasification (+1.5% YoY).",
            "Domestic APM gas ceiling enforced at statutory cap of $7.00 / MMBTU (Kirit Parikh formula), while HP-HT deepwater ceiling remained at $8.90 / MMBTU.",
            "Pradhan Mantri Ujjwala Yojana (PMUY) active beneficiaries reached 10.33 Crore, supported by ₹12,000 Crore targeted budgetary subsidy envelope.",
        ],
        "table1_economic_indicators": [
            {"indicator": "Population (basis RGI projections)", "unit": "Billion", "val_cur": "1.402", "val_prev": "1.390", "yoy": "+0.9%"},
            {"indicator": "GDP at Constant Prices", "unit": "Growth %", "val_cur": "6.8%", "val_prev": "7.6%", "yoy": "-0.8% pts"},
            {"indicator": "Index of Industrial Production (IIP General)", "unit": "Growth %", "val_cur": "4.8%", "val_prev": "5.2%", "yoy": "-0.4% pts"},
            {"indicator": "• IIP - Mining (Weight: 11.05)", "unit": "Growth %", "val_cur": "3.2%", "val_prev": "4.1%", "yoy": "-0.9% pts"},
            {"indicator": "• IIP - Manufacturing (Weight: 76.06)", "unit": "Growth %", "val_cur": "4.9%", "val_prev": "5.0%", "yoy": "-0.1% pts"},
            {"indicator": "• IIP - Electricity (Weight: 10.87)", "unit": "Growth %", "val_cur": "8.1%", "val_prev": "7.9%", "yoy": "+0.2% pts"},
            {"indicator": "CPI Inflation (General)", "unit": "Rate %", "val_cur": "4.3%", "val_prev": "4.8%", "yoy": "-0.5% pts"},
            {"indicator": "WPI Inflation (All Commodities)", "unit": "Rate %", "val_cur": "2.1%", "val_prev": "2.4%", "yoy": "-0.3% pts"},
            {"indicator": "Foreign Exchange Reserves (RBI)", "unit": "USD Billion", "val_cur": "682.4", "val_prev": "651.2", "yoy": "+4.8%"},
            {"indicator": "Merchandise Trade Deficit", "unit": "USD Billion", "val_cur": "-23.5", "val_prev": "-22.8", "yoy": "+3.1%"},
        ],
        "table2_energy_glance": [
            {"item": "Indigenous Crude Production", "unit": "MMT", "aug26": "2.30", "jul26": "2.30", "aug25": "2.43", "mom": "0.0%", "yoy": "-5.3%", "fytd27": "11.50", "fytd26": "12.14", "ytd_chg": "-5.3%"},
            {"item": "Crude Oil Imports", "unit": "MMT", "aug26": "21.60", "jul26": "21.60", "aug25": "19.06", "mom": "0.0%", "yoy": "+13.3%", "fytd27": "102.40", "fytd26": "101.89", "ytd_chg": "+0.5%"},
            {"item": "Total Crude Processed", "unit": "MMT", "aug26": "23.80", "jul26": "23.80", "aug25": "23.33", "mom": "0.0%", "yoy": "+2.0%", "fytd27": "114.20", "fytd26": "115.35", "ytd_chg": "-1.0%"},
            {"item": "Total POL Production", "unit": "MMT", "aug26": "24.80", "jul26": "24.80", "aug25": "24.08", "mom": "0.0%", "yoy": "+3.0%", "fytd27": "118.50", "fytd26": "121.54", "ytd_chg": "-2.5%"},
            {"item": "POL Imports", "unit": "MMT", "aug26": "3.20", "jul26": "3.20", "aug25": "5.39", "mom": "0.0%", "yoy": "-40.6%", "fytd27": "16.80", "fytd26": "30.60", "ytd_chg": "-45.1%"},
            {"item": "POL Exports", "unit": "MMT", "aug26": "5.10", "jul26": "5.10", "aug25": "4.71", "mom": "0.0%", "yoy": "+8.3%", "fytd27": "24.20", "fytd26": "29.33", "ytd_chg": "-17.5%"},
            {"item": "Gross POL Consumption", "unit": "MMT", "aug26": "19.91", "jul26": "19.91", "aug25": "19.35", "mom": "0.0%", "yoy": "+2.9%", "fytd27": "97.71", "fytd26": "101.68", "ytd_chg": "-3.9%"},
            {"item": "Gross Natural Gas Production", "unit": "MMSCM", "aug26": "3,025", "jul26": "3,025", "aug25": "3,050", "mom": "0.0%", "yoy": "-0.8%", "fytd27": "15,120", "fytd26": "15,250", "ytd_chg": "-0.9%"},
            {"item": "LNG Imports (Regasified)", "unit": "MMSCM", "aug26": "2,915", "jul26": "2,915", "aug25": "2,872", "mom": "0.0%", "yoy": "+1.5%", "fytd27": "14,570", "fytd26": "14,350", "ytd_chg": "+1.5%"},
            {"item": "Total Natural Gas Off-take", "unit": "MMSCM", "aug26": "5,740", "jul26": "5,740", "aug25": "5,801", "mom": "0.0%", "yoy": "-1.1%", "fytd27": "28,700", "fytd26": "29,000", "ytd_chg": "-1.0%"},
        ],
        "table3_indigenous_crude": [
            {"regime": "ONGC (Nomination)", "aug26": "1,520", "jul26": "1,520", "aug25": "1,610", "yoy": "-5.6%", "fytd27": "7,600", "fytd26": "8,050"},
            {"regime": "OIL (Nomination)", "aug26": "290", "jul26": "290", "aug25": "295", "yoy": "-1.7%", "fytd27": "1,450", "fytd26": "1,475"},
            {"regime": "Pre-NELP Joint Ventures", "aug26": "270", "jul26": "270", "aug25": "285", "yoy": "-5.3%", "fytd27": "1,350", "fytd26": "1,425"},
            {"regime": "NELP & DSF Rounds", "aug26": "220", "jul26": "220", "aug25": "240", "yoy": "-8.3%", "fytd27": "1,100", "fytd26": "1,200"},
            {"regime": "Total Indigenous Crude & Condensate", "aug26": "2,300", "jul26": "2,300", "aug25": "2,430", "yoy": "-5.3%", "fytd27": "11,500", "fytd26": "12,150"},
        ],
        "table4_overseas_production": [
            {"entity": "Domestic Oil Production", "type": "Crude Oil (MMT)", "aug26": "2.30", "fytd27": "11.50", "share": "73.0%"},
            {"entity": "ONGC Videsh Ltd (OVL) Overseas", "type": "Crude Oil (MMT)", "aug26": "0.85", "fytd27": "4.25", "share": "27.0%"},
            {"entity": "Total Sovereign Crude Assets", "type": "Crude Oil (MMT)", "aug26": "3.15", "fytd27": "15.75", "share": "100.0%"},
            {"entity": "Domestic Gas Production", "type": "Natural Gas (MMSCM)", "aug26": "3,025", "fytd27": "15,120", "share": "86.3%"},
            {"entity": "OVL Overseas Gas Assets", "type": "Natural Gas (MMSCM)", "aug26": "480", "fytd27": "2,400", "share": "13.7%"},
            {"entity": "Total Sovereign Gas Assets", "type": "Natural Gas (MMSCM)", "aug26": "3,505", "fytd27": "17,520", "share": "100.0%"},
        ],
        "table5_crude_processing_diet": [
            {"crude_type": "High Sulphur (HS / Sour Crude)", "volume_mmt": "18.20", "share_pct": "76.5%", "key_grades": "Arab Light, Arab Heavy, Dubai, Oman, Basrah Medium"},
            {"crude_type": "Low Sulphur (LS / Sweet Crude)", "volume_mmt": "5.60", "share_pct": "23.5%", "key_grades": "Dated Brent, Bonny Light, Mumbai High, Assam Crude"},
            {"crude_type": "Total Crude Processed in Refineries", "volume_mmt": "23.80", "share_pct": "100.0%", "key_grades": "Average API: 31.8° · Average Sulphur: 1.62 wt%"},
        ],
        "table6_crude_imports_trade": [
            {"commodity": "Crude Oil Imports", "qty_mmt": "21.60", "val_usd_billion": "$13.70 B", "val_inr_crore": "₹1,15,286 Cr", "fytd_qty_mmt": "102.40", "fytd_val_usd": "$64.80 B"},
            {"commodity": "LNG Imports (Regasified)", "qty_mmt": "2.20", "val_usd_billion": "$1.20 B", "val_inr_crore": "₹10,098 Cr", "fytd_qty_mmt": "10.80", "fytd_val_usd": "$5.90 B"},
            {"commodity": "Gross Hydrocarbon Imports", "qty_mmt": "23.80", "val_usd_billion": "$14.90 B", "val_inr_crore": "₹1,25,384 Cr", "fytd_qty_mmt": "113.20", "fytd_val_usd": "$70.70 B"},
            {"commodity": "Petroleum Products (POL) Exports", "qty_mmt": "5.10", "val_usd_billion": "$5.00 B", "val_inr_crore": "₹42,075 Cr", "fytd_qty_mmt": "24.20", "fytd_val_usd": "$23.80 B"},
            {"commodity": "Net Hydrocarbon Import Bill", "qty_mmt": "18.70", "val_usd_billion": "$11.20 B", "val_inr_crore": "₹83,309 Cr", "fytd_qty_mmt": "89.00", "fytd_val_usd": "$53.40 B"},
        ],
        "table7_self_sufficiency": [
            {"sector": "Crude Oil Self-Sufficiency", "indigenous": "2.30 MMT", "total_req": "23.80 MMT", "import_dependency": "88.2%", "status": "Net Importer"},
            {"sector": "Natural Gas Self-Sufficiency", "indigenous": "2,825 MMSCM", "total_req": "5,740 MMSCM", "import_dependency": "50.8%", "status": "Net Importer"},
            {"sector": "Petroleum Products (POL)", "indigenous": "24.80 MMT", "total_req": "19.91 MMT", "import_dependency": "0.0% (Net Surplus)", "status": "Net Exporter (+4.89 MMT)"},
        ],
        "table8_refineries_capacity": [
            {"sector": "PSU Refineries (IOCL, BPCL, HPCL, MRPL, CPCL, NRL)", "installed_mmtpa": "142.50", "crude_processed_mmt": "12.80", "utilization_pct": "107.8%"},
            {"sector": "Joint Venture (JV) Refineries (BORL Bina, HMEL Bathinda)", "installed_mmtpa": "20.00", "crude_processed_mmt": "3.00", "utilization_pct": "102.5%"},
            {"sector": "Private Refineries (RIL DTA/SEZ Jamnagar, Nayara Vadinar)", "installed_mmtpa": "104.50", "crude_processed_mmt": "8.00", "utilization_pct": "91.9%"},
            {"sector": "All India Total", "installed_mmtpa": "267.00", "crude_processed_mmt": "23.80", "utilization_pct": "104.2%"},
        ],
        "table9_pipelines_network": [
            {"network_type": "Crude Oil Trunk Pipelines", "length_km": "10,420 km", "capacity_mmtpa": "153.2 MMTPA", "utilization_pct": "84.5%", "primary_operators": "IOCL, HPCL, OIL, Cairn"},
            {"network_type": "Petroleum Product Pipelines", "length_km": "23,150 km", "capacity_mmtpa": "128.6 MMTPA", "utilization_pct": "79.2%", "primary_operators": "IOCL, BPCL, HPCL"},
            {"network_type": "LPG Dedicated Pipelines", "length_km": "3,850 km", "capacity_mmtpa": "14.2 MMTPA", "utilization_pct": "82.0%", "primary_operators": "GAIL, IOCL, BPCL"},
        ],
        "table10_grm_margins": [
            {"refinery_entity": "Indian Oil Corporation Ltd (IOCL)", "grm_q1_fy27": ".40 / bbl", "grm_fy26": ".60 / bbl", "complexity_nelson": "10.6"},
            {"refinery_entity": "Bharat Petroleum Corp Ltd (BPCL)", "grm_q1_fy27": ".10 / bbl", "grm_fy26": ".40 / bbl", "complexity_nelson": "10.2"},
            {"refinery_entity": "Hindustan Petroleum Corp Ltd (HPCL)", "grm_q1_fy27": ".90 / bbl", "grm_fy26": ".15 / bbl", "complexity_nelson": "9.8"},
            {"refinery_entity": "Mangalore Refinery & Petrochem (MRPL)", "grm_q1_fy27": ".80 / bbl", "grm_fy26": ".20 / bbl", "complexity_nelson": "11.1"},
            {"refinery_entity": "Chennai Petroleum Corp Ltd (CPCL)", "grm_q1_fy27": ".20 / bbl", "grm_fy26": ".50 / bbl", "complexity_nelson": "9.4"},
            {"refinery_entity": "Reliance Industries Ltd (RIL Jamnagar SEZ)", "grm_q1_fy27": "1.50 / bbl", "grm_fy26": "2.20 / bbl", "complexity_nelson": "21.1"},
            {"refinery_entity": "Nayara Energy Ltd (Vadinar)", "grm_q1_fy27": ".80 / bbl", "grm_fy26": "0.40 / bbl", "complexity_nelson": "12.8"},
            {"refinery_entity": "Singapore Complex Benchmark Average", "grm_q1_fy27": ".40 / bbl", "grm_fy26": ".90 / bbl", "complexity_nelson": "8.0"},
        ],
        "table11a_pol_consumption": [
            {"product": "High Speed Diesel (HSD)", "aug26": "7,023.0", "jul26": "6,980.0", "aug25": "6,575.0", "mom": "+0.6%", "yoy": "+6.8%", "fytd27": "35,420.0", "fytd26": "33,890.0", "ytd_chg": "+4.5%"},
            {"product": "Motor Spirit (Petrol / MS)", "aug26": "3,250.0", "jul26": "3,190.0", "aug25": "2,980.0", "mom": "+1.9%", "yoy": "+9.1%", "fytd27": "16,450.0", "fytd26": "15,430.0", "ytd_chg": "+6.6%"},
            {"product": "Liquefied Petroleum Gas (LPG)", "aug26": "2,450.0", "jul26": "2,420.0", "aug25": "2,510.0", "mom": "+1.2%", "yoy": "-2.4%", "fytd27": "12,180.0", "fytd26": "12,480.0", "ytd_chg": "-2.4%"},
            {"product": "Naphtha", "aug26": "1,180.0", "jul26": "1,160.0", "aug25": "1,220.0", "mom": "+1.7%", "yoy": "-3.3%", "fytd27": "5,820.0", "fytd26": "6,100.0", "ytd_chg": "-4.6%"},
            {"product": "Aviation Turbine Fuel (ATF)", "aug26": "780.0", "jul26": "775.0", "aug25": "740.0", "mom": "+0.6%", "yoy": "+5.4%", "fytd27": "3,890.0", "fytd26": "3,750.0", "ytd_chg": "+3.7%"},
            {"product": "Petroleum Coke (Petcoke)", "aug26": "1,220.0", "jul26": "1,200.0", "aug25": "1,260.0", "mom": "+1.7%", "yoy": "-3.2%", "fytd27": "6,050.0", "fytd26": "6,300.0", "ytd_chg": "-4.0%"},
            {"product": "Bitumen", "aug26": "610.0", "jul26": "590.0", "aug25": "640.0", "mom": "+3.4%", "yoy": "-4.7%", "fytd27": "3,450.0", "fytd26": "3,720.0", "ytd_chg": "-7.3%"},
            {"product": "Furnace Oil & LSHS", "aug26": "540.0", "jul26": "530.0", "aug25": "550.0", "mom": "+1.9%", "yoy": "-1.8%", "fytd27": "2,680.0", "fytd26": "2,740.0", "ytd_chg": "-2.2%"},
            {"product": "Light Diesel Oil (LDO)", "aug26": "65.0", "jul26": "62.0", "aug25": "60.0", "mom": "+4.8%", "yoy": "+8.3%", "fytd27": "310.0", "fytd26": "290.0", "ytd_chg": "+6.9%"},
            {"product": "Lubricants & Greases", "aug26": "380.0", "jul26": "375.0", "aug25": "370.0", "mom": "+1.3%", "yoy": "+2.7%", "fytd27": "1,880.0", "fytd26": "1,840.0", "ytd_chg": "+2.2%"},
            {"product": "Others (Specialty Solvents/Paraffin)", "aug26": "1,108.0", "jul26": "1,088.0", "aug25": "1,055.0", "mom": "+1.8%", "yoy": "+5.0%", "fytd27": "5,440.0", "fytd26": "5,230.0", "ytd_chg": "+4.0%"},
            {"product": "Total Petroleum Products (POL)", "aug26": "18,606.0", "jul26": "18,370.0", "aug25": "18,000.0", "mom": "+1.3%", "yoy": "+3.4%", "fytd27": "93,570.0", "fytd26": "91,770.0", "ytd_chg": "+2.0%"},
        ],
        "table11b_regional_consumption": [
            {"region": "Northern Region (DL, HR, PB, UP, RJ, UT, JK, HP)", "ms_tmt": "1,180.0", "hsd_tmt": "2,450.0", "atf_tmt": "285.0", "lpg_tmt": "820.0", "total_tmt": "4,735.0", "share": "34.8%"},
            {"region": "Western Region (MH, GJ, MP, GA, UT)", "ms_tmt": "980.0", "hsd_tmt": "2,120.0", "atf_tmt": "260.0", "lpg_tmt": "710.0", "total_tmt": "4,070.0", "share": "29.9%"},
            {"region": "Southern Region (TN, KA, AP, TS, KL, PY)", "ms_tmt": "840.0", "hsd_tmt": "1,750.0", "atf_tmt": "185.0", "lpg_tmt": "640.0", "total_tmt": "3,415.0", "share": "25.1%"},
            {"region": "Eastern & NE Region (WB, BR, OD, JH, AS, NE)", "ms_tmt": "250.0", "hsd_tmt": "703.0", "atf_tmt": "50.0", "lpg_tmt": "280.0", "total_tmt": "1,283.0", "share": "9.4%"},
            {"region": "All India Total Key Fuels", "ms_tmt": "3,250.0", "hsd_tmt": "7,023.0", "atf_tmt": "780.0", "lpg_tmt": "2,450.0", "total_tmt": "13,503.0", "share": "100.0%"},
        ],
        "table12_kerosene_allocation": [
            {"state_category": "Allocated States (Non-LPG Saturated PDS)", "allocation_tmt": "90.0", "upliftment_tmt": "85.2", "upliftment_pct": "94.7%", "subsidy_status": "Direct Benefit Transfer"},
            {"state_category": "Kerosene Free States / UTs (12 Jurisdictions)", "allocation_tmt": "0.0", "upliftment_tmt": "0.0", "upliftment_pct": "100.0%", "subsidy_status": "100% PMUY Saturated"},
        ],
        "table13_ethanol_blending": [
            {"metric": "Monthly Ethanol Blending in Petrol (August 2026)", "value": "20.0%", "benchmark_target": "20.0%", "compliance": "100.0% Compliant"},
            {"metric": "Cumulative Blending (ESY Nov 2025 – Aug 2026)", "value": "20.0%", "benchmark_target": "20.0%", "compliance": "100.0% Compliant"},
            {"metric": "Total Ethanol Supplied by Distilleries (ESY to date)", "value": "612 Crore Litres", "benchmark_target": "610 Crore Litres", "compliance": "+0.3% Surplus"},
            {"metric": "Estimated Foreign Exchange Savings (Crude Displacement)", "value": "₹28,500 Crore", "benchmark_target": "₹25,000 Crore", "compliance": "Exceeded Target"},
            {"metric": "Farmer Remittances Disbursed by Sugar / Grain Mills", "value": "₹42,100 Crore", "benchmark_target": "₹40,000 Crore", "compliance": "Disbursed"},
        ],
        "table14_marketing_infrastructure": [
            {"facility": "Retail Outlets (ROs) - PSU OMCs (IOCL, BPCL, HPCL)", "aug26": "82,450", "aug25": "79,800", "net_add": "+2,650"},
            {"facility": "Retail Outlets (ROs) - Private Refiners (RIL, Nayara, Shell)", "aug26": "8,970", "aug25": "8,420", "net_add": "+550"},
            {"facility": "Total Fuel Retail Outlets Network", "aug26": "91,420", "aug25": "88,220", "net_add": "+3,200"},
            {"facility": "LPG Distributorships (Active Network)", "aug26": "25,680", "aug25": "25,380", "net_add": "+300"},
            {"facility": "Aviation Fueling Stations (AFS)", "aug26": "312", "aug25": "298", "net_add": "+14"},
            {"facility": "Bulk Petroleum Storage Depots / Terminals", "aug26": "342", "aug25": "338", "net_add": "+4"},
        ],
        "table15_lpg_consumption_split": [
            {"category": "Domestic Subsidized (14.2 kg & 5 kg cylinders)", "volume_tmt": "2,140.0", "share_pct": "87.3%", "active_base": "32.5 Crore Households"},
            {"category": "Non-Domestic Commercial / Industrial (19 kg cylinders)", "volume_tmt": "310.0", "share_pct": "12.7%", "active_base": "Hotels, Restaurants, Industry"},
            {"category": "Total LPG Consumption", "volume_tmt": "2,450.0", "share_pct": "100.0%", "active_base": "Sovereign Distribution Network"},
        ],
        "table16_lpg_marketing_pmuy": [
            {"parameter": "Total Active Domestic LPG Consumers", "aug26": "32.50 Crore", "aug25": "31.40 Crore", "yoy_growth": "+3.5%"},
            {"parameter": "PMUY Ujjwala Beneficiary Base", "aug26": "10.33 Crore", "aug25": "9.60 Crore", "yoy_growth": "+7.6%"},
            {"parameter": "National LPG Coverage / Penetration Rate", "aug26": "99.8%", "aug25": "99.5%", "yoy_growth": "+0.3% pts"},
            {"parameter": "Annual PMUY Budgetary Envelope (MoF)", "aug26": "₹12,000 Crore", "aug25": "₹11,900 Crore", "yoy_growth": "+0.8%"},
            {"parameter": "Targeted PMUY Subsidy per 14.2kg Refill", "aug26": "₹300.00", "aug25": "₹300.00", "yoy_growth": "Maintained"},
        ],
        "table17_lpg_regional_refills": [
            {"region": "Northern Region", "pmuy_customers_cr": "3.42", "avg_refills_year": "3.8 refills", "active_distributors": "7,850"},
            {"region": "Eastern Region", "pmuy_customers_cr": "3.25", "avg_refills_year": "3.6 refills", "active_distributors": "6,420"},
            {"region": "Western Region", "pmuy_customers_cr": "2.12", "avg_refills_year": "4.1 refills", "active_distributors": "5,680"},
            {"region": "Southern Region", "pmuy_customers_cr": "1.54", "avg_refills_year": "4.4 refills", "active_distributors": "5,730"},
            {"region": "All India Total", "pmuy_customers_cr": "10.33", "avg_refills_year": "3.9 refills", "active_distributors": "25,680"},
        ],
        "table18_natural_gas_balance": [
            {"component": "Gross Indigenous Natural Gas Production", "volume_mmscm": "3,025", "share_pct": "52.7%", "primary_sources": "ONGC (2,120), OIL (285), Private/JVs (620)"},
            {"component": "Less: Flared / Internal Gas Fuel Extraction", "volume_mmscm": "-200", "share_pct": "-3.5%", "primary_sources": "Field compressor fuel and technical loss"},
            {"component": "Net Domestic Natural Gas Available", "volume_mmscm": "2,825", "share_pct": "49.2%", "primary_sources": "Administered & Non-APM allocation"},
            {"component": "LNG Imports (Regasified RLNG)", "volume_mmscm": "2,915", "share_pct": "50.8%", "primary_sources": "Long-term Qatar/Australia + Spot cargoes"},
            {"component": "Total Natural Gas Domestic Off-take", "volume_mmscm": "5,740", "share_pct": "100.0%", "primary_sources": "Fertilizer (32%), CGD (33%), Power (14%), Refinery (12%), Others (9%)"},
        ],
        "table19_cbm_development": [
            {"cbm_block": "Raniganj East & South (Essar Oil & Gas)", "state": "West Bengal", "aug26_mmscm": "28.5", "fytd_mmscm": "142.5", "status": "Commercial Production"},
            {"cbm_block": "Sohagpur West & East (Reliance Industries)", "state": "Madhya Pradesh", "aug26_mmscm": "22.4", "fytd_mmscm": "112.0", "status": "Commercial Production"},
            {"cbm_block": "Jharia & Bokaro Blocks (ONGC)", "state": "Jharkhand", "aug26_mmscm": "7.5", "fytd_mmscm": "37.5", "status": "Developmental Phase"},
            {"cbm_block": "All India Total CBM Production", "state": "Pan-India", "aug26_mmscm": "58.4", "fytd_mmscm": "292.0", "status": "Prognosticated: 2,600 BCM"},
        ],
        "table20_gas_pipeline_network": [
            {"operator": "GAIL (India) Limited (HVJ, DVPL, CJPL, JHBDPL, Kochi-Bengaluru)", "operational_km": "16,100 km", "capacity_mmscmd": "212.0 MMSCMD", "utilization_pct": "64.5%"},
            {"operator": "Gujarat State Petronet Ltd (GSPL Network)", "operational_km": "2,750 km", "capacity_mmscmd": "54.0 MMSCMD", "utilization_pct": "71.2%"},
            {"operator": "Pipeline Infrastructure Ltd (East-West Pipeline / EWPL)", "operational_km": "1,480 km", "capacity_mmscmd": "85.0 MMSCMD", "utilization_pct": "38.4%"},
            {"operator": "Indian Oil Corporation Ltd (IOCL Ennore Pipelines)", "operational_km": "1,420 km", "capacity_mmscmd": "20.0 MMSCMD", "utilization_pct": "42.0%"},
            {"operator": "Others (AGCL, ONGC, GGL)", "operational_km": "2,050 km", "capacity_mmscmd": "14.0 MMSCMD", "utilization_pct": "55.0%"},
            {"operator": "Total National Gas Grid (Operational)", "operational_km": "23,800 km", "capacity_mmscmd": "385.0 MMSCMD", "utilization_pct": "61.2%"},
        ],
        "table21_lng_terminals": [
            {"terminal_name": "Dahej Terminal (Petronet LNG)", "state": "Gujarat", "capacity_mmtpa": "17.5 MMTPA", "utilization_pct": "95.0%", "sendout_mmscmd": "58.2 MMSCMD"},
            {"terminal_name": "Hazira Terminal (Shell Energy)", "state": "Gujarat", "capacity_mmtpa": "5.2 MMTPA", "utilization_pct": "82.0%", "sendout_mmscmd": "14.5 MMSCMD"},
            {"terminal_name": "Dabhol Terminal (Konkan LNG / GAIL)", "state": "Maharashtra", "capacity_mmtpa": "5.0 MMTPA", "utilization_pct": "48.0%", "sendout_mmscmd": "7.8 MMSCMD"},
            {"terminal_name": "Kochi Terminal (Petronet LNG)", "state": "Kerala", "capacity_mmtpa": "5.0 MMTPA", "utilization_pct": "24.0%", "sendout_mmscmd": "4.2 MMSCMD"},
            {"terminal_name": "Ennore Terminal (Indian Oil LNG)", "state": "Tamil Nadu", "capacity_mmtpa": "5.0 MMTPA", "utilization_pct": "38.0%", "sendout_mmscmd": "6.1 MMSCMD"},
            {"terminal_name": "Dhamra Terminal (Adani Total LNG)", "state": "Odisha", "capacity_mmtpa": "5.0 MMTPA", "utilization_pct": "55.0%", "sendout_mmscmd": "8.8 MMSCMD"},
            {"terminal_name": "Total All India Regasification Infrastructure", "state": "National", "capacity_mmtpa": "42.7 MMTPA", "utilization_pct": "67.8%", "sendout_mmscmd": "99.6 MMSCMD"},
        ],
        "table22_cgd_infrastructure": [
            {"parameter": "Authorized Geographical Areas (GAs under PNGRB)", "aug26": "307 GAs", "aug25": "300 GAs", "coverage_pct": "98.0% Population"},
            {"parameter": "Operational CNG Stations", "aug26": "6,850", "aug25": "5,980", "coverage_pct": "+14.5% YoY"},
            {"parameter": "Domestic PNG Connections (Households)", "aug26": "1.35 Crore", "aug25": "1.18 Crore", "coverage_pct": "+14.4% YoY"},
            {"parameter": "Commercial & Industrial PNG Customers", "aug26": "48,200", "aug25": "42,100", "coverage_pct": "+14.5% YoY"},
            {"parameter": "Steel Pipeline Network (Inch-Km laid by CGD entities)", "aug26": "1,18,500 km", "aug25": "1,04,200 km", "coverage_pct": "+13.7% YoY"},
        ],
        "table23_domestic_gas_prices": [
            {"pricing_regime": "Administered Pricing Mechanism (APM) - Nomination Fields", "formula_basis": "10% of prior month ICB (0.19 = .02/MMBTU)", "effective_price": ".00 / MMBTU", "statutory_status": "Capped at Statutory Ceiling (.00/MMBTU)"},
            {"pricing_regime": "APM Gas Floor Price (Kirit Parikh Committee)", "formula_basis": "Statutory Minimum Floor Protection", "effective_price": ".00 / MMBTU", "statutory_status": "Floor Preserved"},
            {"pricing_regime": "High Pressure-High Temperature (HP-HT) Deepwater Fields", "formula_basis": "Bi-Annual Formula based on Fuel Oil, Naphtha, LNG", "effective_price": ".90 / MMBTU", "statutory_status": "Statutory Deepwater Cap Enforced"},
            {"pricing_regime": "Imported Spot LNG (RLNG at Ex-Terminal)", "formula_basis": "JKM Benchmark + Freight + Regasification", "effective_price": "2.40 / MMBTU", "statutory_status": "Market Determined"},
        ],
        "table24_metro_cng_png_prices": [
            {"city": "Delhi (Indraprastha Gas Limited - IGL)", "cng_price": "₹75.09 / kg", "png_domestic": "₹48.59 / SCM", "state_vat_cng": "12.5%"},
            {"city": "Mumbai (Mahanagar Gas Limited - MGL)", "cng_price": "₹76.00 / kg", "png_domestic": "₹49.00 / SCM", "state_vat_cng": "13.5%"},
            {"city": "Ahmedabad (Adani Total Gas / GGL)", "cng_price": "₹79.34 / kg", "png_domestic": "₹50.23 / SCM", "state_vat_cng": "15.0%"},
            {"city": "Bengaluru (GAIL Gas Limited)", "cng_price": "₹82.50 / kg", "png_domestic": "₹52.50 / SCM", "state_vat_cng": "18.0%"},
            {"city": "Kolkata (Bengal Gas Company Ltd)", "cng_price": "₹84.00 / kg", "png_domestic": "₹53.00 / SCM", "state_vat_cng": "14.0%"},
        ],
        "table25_pricing_tax_buildup": {
            "upstream_benchmarks": [
                {"benchmark": "Dated Brent Crude Spot", "quote_usd": "$90.84 / bbl", "equivalent_inr": "₹7,644.19 / bbl", "source": "ICE Futures & S&P Platts"},
                {"benchmark": "Oman / Dubai Sour Average", "quote_usd": "$89.98 / bbl", "equivalent_inr": "₹7,571.82 / bbl", "source": "Platts & Argus Assessments"},
                {"benchmark": "Indian Basket Crude (ICB Composite)", "quote_usd": "$90.19 / bbl", "equivalent_inr": "₹7,589.50 / bbl", "source": "PPAC Ready Reckoner (75.6% Sour : 24.4% Sweet)"},
                {"benchmark": "RBI Reference Exchange Rate", "quote_usd": "1 USD", "equivalent_inr": "₹84.15", "source": "Reserve Bank of India (RBI)"},
            ],
            "delhi_petrol_buildup": [
                {"element": "Base Refinery Price (including Entry Freight)", "inr_litre": "₹58.20", "share_pct": "57.0%"},
                {"element": "Inland Freight & Marketing Terminal Charges", "inr_litre": "₹0.30", "share_pct": "0.3%"},
                {"element": "Price Charged to Dealers (Excl. Taxes)", "inr_litre": "₹58.50", "share_pct": "57.3%"},
                {"element": "Central Excise Duty (Government of India)", "inr_litre": "₹19.90", "share_pct": "19.5%"},
                {"element": "Dealer Commission (Average across pumps)", "inr_litre": "₹4.13", "share_pct": "4.0%"},
                {"element": "State Value Added Tax (VAT - NCT Delhi @ 19.4%)", "inr_litre": "₹16.59", "share_pct": "16.2%"},
                {"element": "Retail Selling Price (RSP) at Delhi", "inr_litre": "₹102.12", "share_pct": "100.0%"},
            ],
            "delhi_diesel_buildup": [
                {"element": "Base Refinery Price (including Entry Freight)", "inr_litre": "₹59.80", "share_pct": "62.8%"},
                {"element": "Inland Freight & Marketing Terminal Charges", "inr_litre": "₹0.28", "share_pct": "0.3%"},
                {"element": "Price Charged to Dealers (Excl. Taxes)", "inr_litre": "₹60.08", "share_pct": "63.1%"},
                {"element": "Central Excise Duty (Government of India)", "inr_litre": "₹15.80", "share_pct": "16.6%"},
                {"element": "Dealer Commission (Average across pumps)", "inr_litre": "₹3.41", "share_pct": "3.6%"},
                {"element": "State Value Added Tax (VAT - NCT Delhi @ 16.75% + Air Amb. Chg)", "inr_litre": "₹13.91", "share_pct": "14.6%"},
                {"element": "Retail Selling Price (RSP) at Delhi", "inr_litre": "₹95.20", "share_pct": "100.0%"},
            ],
            "metro_comparison": [
                {"metro": "Delhi", "petrol_inr_l": "₹102.12", "diesel_inr_l": "₹95.20", "lpg_domestic_cylinder": "₹942.00"},
                {"metro": "Mumbai", "petrol_inr_l": "₹104.21", "diesel_inr_l": "₹92.15", "lpg_domestic_cylinder": "₹942.50"},
                {"metro": "Kolkata", "petrol_inr_l": "₹103.94", "diesel_inr_l": "₹90.76", "lpg_domestic_cylinder": "₹969.00"},
                {"metro": "Chennai", "petrol_inr_l": "₹100.75", "diesel_inr_l": "₹92.34", "lpg_domestic_cylinder": "₹958.50"},
            ],
        },
        "table26_psu_capex": [
            {"psu_entity": "Oil and Natural Gas Corporation (ONGC)", "annual_budget": "₹34,000 Cr", "actual_spent_aug26": "₹14,250 Cr", "achievement_pct": "41.9%", "major_projects": "KG-DWN-98/2 Deepwater, Mumbai High Redevelopment"},
            {"psu_entity": "Indian Oil Corporation Ltd (IOCL)", "annual_budget": "₹31,000 Cr", "actual_spent_aug26": "₹13,100 Cr", "achievement_pct": "42.3%", "major_projects": "Panipat Refinery Expansion (25 MMTPA), Paradip Petrochem"},
            {"psu_entity": "Bharat Petroleum Corp Ltd (BPCL)", "annual_budget": "₹15,000 Cr", "actual_spent_aug26": "₹6,200 Cr", "achievement_pct": "41.3%", "major_projects": "Bina Refinery Petrochemical Expansion, CGD Network"},
            {"psu_entity": "Hindustan Petroleum Corp Ltd (HPCL)", "annual_budget": "₹14,500 Cr", "actual_spent_aug26": "₹6,150 Cr", "achievement_pct": "42.4%", "major_projects": "Barmer Rajasthan Refinery (9 MMTPA JV), Vizag Modernization"},
            {"psu_entity": "GAIL (India) Limited", "annual_budget": "₹11,500 Cr", "actual_spent_aug26": "₹4,850 Cr", "achievement_pct": "42.2%", "major_projects": "Urja Ganga JHBDPL Pipeline, Usar Polypropylene Plant"},
            {"psu_entity": "Oil India Limited (OIL)", "annual_budget": "₹6,000 Cr", "actual_spent_aug26": "₹2,300 Cr", "achievement_pct": "38.3%", "major_projects": "Numaligarh Expansion (9 MMTPA), Assam Exploration"},
            {"psu_entity": "Total PSU Oil Sector CAPEX", "annual_budget": "₹1,12,000 Cr", "actual_spent_aug26": "₹46,850 Cr", "achievement_pct": "41.8%", "major_projects": "Target on schedule across upstream, refining, and gas grids"},
        ],
        "table27_conversion_factors": [
            {"dimension": "Crude Oil Volume Multiplier", "conversion": "1 Metric Tonne (MT) = 7.33 Barrels (bbl) for Indian Basket (API ~31.8°)"},
            {"dimension": "Barrel to Litre", "conversion": "1 Barrel = 158.987 Litres = 42 US Gallons"},
            {"dimension": "Natural Gas Volume to Energy", "conversion": "1 Million Metric Standard Cubic Metres per Day (MMSCMD) = 0.85 MMTPA LNG equivalent"},
            {"dimension": "Natural Gas Energy Equivalents", "conversion": "1 Metric Standard Cubic Metre (SCM) ≈ 35,300 BTU ≈ 0.0353 MMBTU (at 8,900 kcal/SCM GCV)"},
            {"dimension": "LPG Density Conversion", "conversion": "1 Metric Tonne LPG ≈ 1,835 Litres (at 15°C, 50:50 Propane-Butane commercial blend)"},
            {"dimension": "Standard Currency Multiplier", "conversion": "1 Crore = 10 Million = 10,000,000 | 1 Lakh = 100,000 | 1 Billion = 100 Crore"},
        ],
    }
